/* Mémo modifiable par l'équipe du fonds — versions privées (10/10/2026).
 *
 * Pour TOUT lecteur : si l'équipe a modifié le mémo depuis la publication statique,
 * la dernière version remplace le contenu de la page aussitôt (la page statique la
 * rattrape ~3 min plus tard).
 * Pour un membre de l'équipe du fonds connecté (session signée du code email) :
 * « Modifier » sur chaque section, badge « modifié par … », historique des versions
 * avec aperçu et restauration. Rien ne s'affiche pour les autres lecteurs.
 * Chargé par proplace-chat-memo.js (déjà présent sur toutes les pages de mémo).
 */
(function () {
  'use strict';
  if (window.PPMemoEditor) return;
  var meta = document.querySelector('meta[name="stan-deal"]');
  var area = document.querySelector('.content-area');
  if (!meta || !area) return;
  var ctx;
  try { ctx = JSON.parse(meta.content); } catch (_) { return; }
  var record = ctx.airtable_record || ctx.deal_id || '';
  if (!/^rec[a-zA-Z0-9]{10,30}$/.test(record)) return;
  var API = (window.__PP_MEMO_EDITS_API__ || 'https://alexandre-79537--memo-edits-fastapi-app.modal.run') + '/memos/' + record;
  var en = (document.documentElement.lang || 'fr').toLowerCase().indexOf('en') === 0;
  var T = en ? {
    edit: 'Edit', editMemo: '✏️ Edit the memo', stopEdit: '✓ Done editing', versions: '🕘 Versions', save: 'Save', cancel: 'Cancel',
    saved: function (n) { return 'Saved — version ' + n + '. The public page catches up in about 3 min.'; },
    conflict: function (by) { return 'The memo was changed by ' + by + ' in the meantime. Copy your text, then reload the latest version.'; },
    reload: 'Load the latest version', editedBy: function (who, when) { return 'Edited by ' + who + ' · ' + when; },
    viewing: function (n, when) { return 'You are viewing version ' + n + ' of ' + when + ' (read only).'; },
    restore: 'Restore this version', backToLatest: 'Back to the latest', show: 'View', current: 'current',
    restored: function (n) { return 'Version restored as version ' + n + '.'; }, close: 'Close', error: 'Could not save: ',
    kinds: { generated: 'Generated by Stan', edit: 'Edited by', stan: 'Proposed by Stan, approved by', restore: 'Restored by' },
    link: 'Link URL (https://…)', bold: 'Bold', italic: 'Italic', list: 'Bulleted list', linkBtn: 'Link',
    title: 'Memo versions', sections: 'sections'
  } : {
    edit: 'Modifier', editMemo: '✏️ Modifier le mémo', stopEdit: '✓ Terminer', versions: '🕘 Versions', save: 'Enregistrer', cancel: 'Annuler',
    saved: function (n) { return 'Enregistré — version ' + n + '. La page publique sera à jour dans ~3 min.'; },
    conflict: function (by) { return 'Le mémo a été modifié par ' + by + ' entre-temps. Copiez votre texte, puis rechargez la dernière version.'; },
    reload: 'Charger la dernière version', editedBy: function (who, when) { return 'Modifié par ' + who + ' · ' + when; },
    viewing: function (n, when) { return 'Vous regardez la version ' + n + ' du ' + when + ' (lecture seule).'; },
    restore: 'Restaurer cette version', backToLatest: 'Revenir à la dernière', show: 'Afficher', current: 'actuelle',
    restored: function (n) { return 'Version restaurée : c’est maintenant la version ' + n + '.'; }, close: 'Fermer', error: 'Enregistrement impossible : ',
    kinds: { generated: 'Générée par Stan', edit: 'Modifiée par', stan: 'Proposée par Stan, validée par', restore: 'Restaurée par' },
    link: 'Adresse du lien (https://…)', bold: 'Gras', italic: 'Italique', list: 'Liste à puces', linkBtn: 'Lien',
    title: 'Versions du mémo', sections: 'sections'
  };
  var state = { head: null, role: '', email: '', editing: false, open: null, preview: 0 };
  window.PPMemoEditor = { version: 4, state: state };

  function el(tag, attrs, text) {
    var node = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) { node.setAttribute(k, attrs[k]); });
    if (text != null) node.textContent = text;
    return node;
  }
  function session() {
    try {
      var cookie = document.cookie.split('; ').find(function (c) { return c.indexOf('proplace_auth=') === 0; });
      if (!cookie) return '';
      var auth = JSON.parse(atob(decodeURIComponent(cookie.slice('proplace_auth='.length))));
      return auth && typeof auth.member_session === 'string' ? auth.member_session : '';
    } catch (_) { return ''; }
  }
  function api(path, method, body) {
    var headers = { 'Content-Type': 'application/json' };
    var s = session();
    if (s) headers['X-Member-Session'] = s;
    return fetch(API + path, { method: method || 'GET', headers: headers, credentials: 'omit',
      body: body ? JSON.stringify(body) : undefined })
      .then(function (r) { return r.json().catch(function () { return {}; }).then(function (j) { j.status = r.status; return j; }); });
  }
  function pageVersion() {
    var m = document.querySelector('meta[name="pp-memo-version"]');
    return m ? parseInt(m.getAttribute('content'), 10) || 0 : 0;
  }
  function setPageVersion(n) {
    var m = document.querySelector('meta[name="pp-memo-version"]');
    if (!m) { m = el('meta', { name: 'pp-memo-version' }); document.head.appendChild(m); }
    m.setAttribute('content', String(n));
  }
  function when(iso) {
    var d = new Date(iso || '');
    if (isNaN(d.getTime())) return '';
    return d.toLocaleString(en ? 'en-GB' : 'fr-FR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' });
  }
  function shortWho(email) { return String(email || '').split('@')[0] || 'Stan'; }
  function sections() { return Array.prototype.slice.call(area.querySelectorAll('.section-container[id]')); }
  function toast(text, actions) {
    var old = document.querySelector('.ppme-toast');
    if (old) old.remove();
    var box = el('div', { class: 'ppme-toast', role: 'status' });
    box.appendChild(el('span', {}, text));
    (actions || []).forEach(function (a) {
      var b = el('button', { type: 'button' }, a.label);
      b.onclick = function () { box.remove(); a.run(); };
      box.appendChild(b);
    });
    var x = el('button', { type: 'button', class: 'ppme-x', 'aria-label': T.close }, '×');
    x.onclick = function () { box.remove(); };
    box.appendChild(x);
    document.body.appendChild(box);
    if (!actions) setTimeout(function () { box.remove(); }, 7000);
  }

  /* ── la dernière version pour tout lecteur ─────────────────────────────── */
  function swapArea(html) {
    area.innerHTML = html;
    // des scripts insérés par innerHTML ne s'exécutent pas : on les rejoue (graphiques, plan d'action)
    Array.prototype.forEach.call(area.querySelectorAll('script'), function (old) {
      var s = document.createElement('script');
      Array.prototype.forEach.call(old.attributes, function (a) { s.setAttribute(a.name, a.value); });
      s.text = old.text;
      old.parentNode.replaceChild(s, old);
    });
  }
  function loadVersion(n, asHead) {
    return api('/content' + (asHead ? '' : '?n=' + n)).then(function (c) {
      if (!c.ok || !c.content_area) return null;
      swapArea(c.content_area);
      if (asHead) setPageVersion(c.n);
      decorate();
      return c;
    });
  }
  function syncLatest() {
    return api('/head').then(function (h) {
      if (!h.ok) return;
      state.head = h;
      var mine = pageVersion();
      if (mine ? mine < h.n : h.edited) return loadVersion(h.n, true);
    }).catch(function () {});
  }

  /* ── l'équipe du fonds : modifier, badges, versions ─────────────────────── */
  function decorate() {
    sections().forEach(function (sec) {
      Array.prototype.forEach.call(sec.querySelectorAll(':scope > .ppme-ui'), function (n) { n.remove(); });
      if (!state.role || state.preview) return;
      sec.classList.add('ppme-sec');
      var by = sec.getAttribute('data-pp-edited-by');
      if (by) {
        var badge = el('div', { class: 'ppme-ui ppme-badge' }, T.editedBy(shortWho(by), when(sec.getAttribute('data-pp-edited-at'))));
        var title = sec.querySelector(':scope > h2, :scope > .section-title');
        if (title && title.nextSibling) sec.insertBefore(badge, title.nextSibling); else sec.insertBefore(badge, sec.firstChild);
      }
      if (state.editing) {
        var btn = el('button', { type: 'button', class: 'ppme-ui ppme-edit' }, '✏️ ' + T.edit);
        btn.onclick = function () { startEdit(sec); };
        sec.insertBefore(btn, sec.firstChild);
      }
    });
  }
  function cleanHtml(sec) {
    var clone = sec.cloneNode(true);
    Array.prototype.forEach.call(clone.querySelectorAll('.ppme-ui'), function (n) { n.remove(); });
    return clone.innerHTML;
  }
  function startEdit(sec) {
    if (state.open) return;
    Array.prototype.forEach.call(sec.querySelectorAll(':scope > .ppme-ui'), function (n) { n.remove(); });
    state.open = { sec: sec, before: sec.innerHTML };
    sec.classList.add('ppme-editing');
    var bar = el('div', { class: 'ppme-ui ppme-toolbar', contenteditable: 'false' });
    [['bold', 'B', T.bold], ['italic', 'I', T.italic], ['insertUnorderedList', '•', T.list], ['createLink', '🔗', T.linkBtn]]
      .forEach(function (c) {
        var b = el('button', { type: 'button', title: c[2], 'aria-label': c[2] }, c[1]);
        b.onmousedown = function (e) { e.preventDefault(); };
        b.onclick = function () {
          if (c[0] === 'createLink') {
            var url = window.prompt(T.link, 'https://');
            if (url && /^https?:\/\//i.test(url)) document.execCommand('createLink', false, url);
          } else document.execCommand(c[0], false, null);
        };
        bar.appendChild(b);
      });
    var save = el('button', { type: 'button', class: 'ppme-save' }, T.save);
    var cancel = el('button', { type: 'button', class: 'ppme-cancel' }, T.cancel);
    save.onclick = saveEdit;
    cancel.onclick = cancelEdit;
    bar.appendChild(save);
    bar.appendChild(cancel);
    sec.insertBefore(bar, sec.firstChild);
    sec.setAttribute('contenteditable', 'true');
    sec.focus();
  }
  function closeEdit() {
    var sec = state.open.sec;
    sec.removeAttribute('contenteditable');
    sec.classList.remove('ppme-editing');
    state.open = null;
  }
  function cancelEdit() {
    var sec = state.open.sec;
    sec.innerHTML = state.open.before;
    closeEdit();
    decorate();
  }
  function saveEdit() {
    var sec = state.open.sec;
    var html = cleanHtml(sec);
    var base = pageVersion() || (state.head && state.head.n) || 0;
    api('/edit', 'POST', { base: base, section_id: sec.id, html: html }).then(function (j) {
      if (j.ok) {
        closeEdit();
        setPageVersion(j.n);
        state.head = j;
        sec.setAttribute('data-pp-edited-by', state.email);
        sec.setAttribute('data-pp-edited-at', j.at || '');
        decorate();
        toast(T.saved(j.n));
      } else if (j.status === 409 && j.head) {
        toast(T.conflict(shortWho(j.head.by)), [{ label: T.reload, run: function () {
          closeEdit(); loadVersion(j.head.n, true);
        } }]);
      } else {
        toast(T.error + (j.detail || j.error || j.status));
      }
    }).catch(function (e) { toast(T.error + e); });
  }
  function kindLabel(v) {
    var k = T.kinds[v.kind] || v.kind;
    return v.kind === 'generated' ? k : k + ' ' + shortWho(v.by);
  }
  function openVersions() {
    api('/versions').then(function (j) {
      if (!j.ok) { toast(T.error + (j.detail || j.status)); return; }
      var old = document.querySelector('.ppme-modal');
      if (old) old.remove();
      var modal = el('div', { class: 'ppme-modal', role: 'dialog', 'aria-modal': 'true', 'aria-label': T.title });
      var card = el('div', { class: 'ppme-card' });
      var head = el('div', { class: 'ppme-card-h' });
      head.appendChild(el('strong', {}, T.title));
      var x = el('button', { type: 'button', class: 'ppme-x', 'aria-label': T.close }, '×');
      x.onclick = function () { modal.remove(); };
      head.appendChild(x);
      card.appendChild(head);
      var list = el('ol', { class: 'ppme-list' });
      (j.versions || []).forEach(function (v, i) {
        var li = el('li');
        li.appendChild(el('span', { class: 'ppme-n' }, 'v' + v.n));
        var titles = (v.sections || []).map(function (id) {
          var t = document.querySelector('#' + CSS.escape(id) + ' .section-title, #' + CSS.escape(id) + ' h2');
          return t ? t.textContent.trim() : id;
        });
        var text = el('span', { class: 'ppme-what' }, kindLabel(v) + ' · ' + when(v.at)
          + (titles.length ? ' · ' + titles.join(', ') : '') + (v.note ? ' — ' + v.note : ''));
        li.appendChild(text);
        if (i === 0) li.appendChild(el('span', { class: 'ppme-cur' }, T.current));
        else {
          var show = el('button', { type: 'button' }, T.show);
          show.onclick = function () { modal.remove(); preview(v); };
          li.appendChild(show);
        }
        list.appendChild(li);
      });
      card.appendChild(list);
      modal.appendChild(card);
      modal.onclick = function (e) { if (e.target === modal) modal.remove(); };
      document.body.appendChild(modal);
    });
  }
  function preview(v) {
    loadVersion(v.n, false).then(function (c) {
      if (!c) return;
      state.preview = v.n;
      decorate();
      var bar = el('div', { class: 'ppme-preview', role: 'status' });
      bar.appendChild(el('span', {}, T.viewing(v.n, when(v.at))));
      var restore = el('button', { type: 'button', class: 'ppme-save' }, T.restore);
      var back = el('button', { type: 'button' }, T.backToLatest);
      restore.onclick = function () {
        api('/restore', 'POST', { base: state.head ? state.head.n : 0, n: v.n }).then(function (j) {
          bar.remove(); state.preview = 0;
          if (j.ok) { state.head = j; loadVersion(j.n, true).then(function () { toast(T.restored(j.n)); }); }
          else if (j.status === 409 && j.head) { loadVersion(j.head.n, true); toast(T.conflict(shortWho(j.head.by))); }
          else toast(T.error + (j.detail || j.error || j.status));
        });
      };
      back.onclick = function () { bar.remove(); state.preview = 0; loadVersion(0, true); };
      bar.appendChild(restore);
      bar.appendChild(back);
      document.body.appendChild(bar);
    });
  }
  /* ── Stan chat : réponses et modifications proposées, validées par l'équipe ── */
  var BLOCKS = 'p, li, h3, h4, tr, blockquote, figcaption';
  var C = en ? {
    chat: '💬 Stan', tab: 'Chat', hint: 'Ask anything about this deal. Stan answers, proposes memo changes you approve, and the results of his actions land here.',
    placeholder: 'e.g. “Rewrite the verdict with what we learned on the call: the CEO wants to sell in 2027”',
    send: 'Send', thinking: 'Stan is thinking…', accept: 'Accept', decline: 'Decline', view: 'Show in memo',
    accepted: 'Accepted', declined: 'Declined', applied: function (n) { return 'Stan’s change applied — version ' + n + '.'; },
    actions: { replace: 'Rewrite', insert_after: 'Add after', 'delete': 'Remove' }, you: 'You', cost: 'cost'
  } : {
    chat: '💬 Stan', tab: 'Chat', hint: 'Demandez n’importe quoi sur ce dossier : Stan répond, propose des modifications du mémo que vous validez, et les résultats de ses actions arrivent ici.',
    placeholder: 'ex. « Réécris le verdict avec ce qu’on a appris à l’appel : le dirigeant veut céder en 2027 »',
    send: 'Envoyer', thinking: 'Stan réfléchit…', accept: 'Accepter', decline: 'Refuser', view: 'Voir dans le mémo',
    accepted: 'Acceptée', declined: 'Refusée', applied: function (n) { return 'Modification de Stan appliquée — version ' + n + '.'; },
    actions: { replace: 'Réécrire', insert_after: 'Ajouter après', 'delete': 'Retirer' }, you: 'Vous', cost: 'coût'
  };
  var chat = { list: null, input: null, loaded: false, decisions: {} };
  function sectionTitle(id) {
    var t = document.querySelector('#' + CSS.escape(id) + ' .section-title, #' + CSS.escape(id) + ' h2');
    return t ? t.textContent.trim() : id;
  }
  function blockNode(op) {
    var sec = document.getElementById(op.section);
    if (!sec) return null;
    var nodes = Array.prototype.filter.call(sec.querySelectorAll(BLOCKS), function (n) { return !n.closest('.ppme-ui'); });
    return nodes[op.index] || null;
  }
  function plain(html) { var d = document.createElement('div'); d.innerHTML = html || ''; return d.textContent.trim(); }
  function proposalCard(prop) {
    var card = el('div', { class: 'ppme-prop' });
    card.appendChild(el('strong', {}, prop.title || 'Proposition'));
    if (prop.why) card.appendChild(el('p', { class: 'ppme-why' }, prop.why));
    (prop.ops || []).forEach(function (op) {
      var row = el('div', { class: 'ppme-op' });
      row.appendChild(el('div', { class: 'ppme-op-h' }, (C.actions[op.action] || op.action) + ' · ' + sectionTitle(op.section)));
      if (op.action !== 'insert_after' && op.before) row.appendChild(el('div', { class: 'ppme-before' }, op.before));
      if (op.action !== 'delete') row.appendChild(el('div', { class: 'ppme-after' }, plain(op.html)));
      var view = el('button', { type: 'button', class: 'ppme-link' }, C.view);
      view.onclick = function () { highlight(blockNode(op)); };
      row.appendChild(view);
      card.appendChild(row);
    });
    var status = chat.decisions[prop.id];
    if (status) {
      card.appendChild(el('span', { class: 'ppme-status ' + status }, status === 'accepted' ? C.accepted : C.declined));
      return card;
    }
    var bar = el('div', { class: 'ppme-prop-actions' });
    var ok = el('button', { type: 'button', class: 'ppme-save' }, C.accept);
    var no = el('button', { type: 'button' }, C.decline);
    ok.onclick = function () {
      ok.disabled = no.disabled = true;
      api('/proposals/' + prop.id + '/accept', 'POST', { base: pageVersion() || (state.head && state.head.n) || 0 }).then(function (j) {
        if (j.ok) {
          chat.decisions[prop.id] = 'accepted';
          state.head = j;
          loadVersion(j.n, true).then(function () { toast(C.applied(j.n)); });
          card.replaceWith(proposalCard(prop));
          renderNba();
        } else {
          ok.disabled = no.disabled = false;
          toast(T.error + (j.detail || j.error || j.status));
        }
      });
    };
    no.onclick = function () {
      api('/proposals/' + prop.id + '/decline', 'POST', {}).then(function () {
        chat.decisions[prop.id] = 'declined';
        card.replaceWith(proposalCard(prop));
      });
    };
    bar.appendChild(ok);
    bar.appendChild(no);
    card.appendChild(bar);
    return card;
  }
  function renderMessage(m) {
    if (m.type !== 'message' || !chat.list) return;
    var mine = m.role === 'user';
    var box = el('div', { class: 'ppme-msg ' + (mine ? 'me' : 'stan') + (m.kind ? ' ppme-' + m.kind : '') });
    box.appendChild(el('div', { class: 'ppme-who' }, (mine ? (m.by === state.email ? C.you : shortWho(m.by)) : 'Stan') + ' · ' + when(m.at)
      + (!mine && m.cost ? ' · ' + C.cost + ' ' + Number(m.cost).toFixed(2) + ' $' : '')
      + (!mine && m.cost_eur ? ' · ' + C.cost + ' ' + fmtEur(m.cost_eur) + ' €' : '')));
    if (m.kind === 'deliverable') renderDeliverable(box, m);
    else if (m.kind === 'research') renderResearch(box, m, m.action && m.action.title);
    else if (m.kind === 'agent_draft') renderAgentDraft(box, m);
    else if (m.kind === 'agent_result') renderAgentResult(box, m);
    else if (m.kind === 'next_action') box.appendChild(el('div', { class: 'ppme-text' }, '🎯 ' + (m.action && m.action.mode === 'agent' ? N.didAgent : N.did)
      + ((m.action && m.action.title) || m.text || '')));
    else if (m.kind === 'agent_build' || m.kind === 'agent_run') box.appendChild(el('div', { class: 'ppme-text' }, (m.kind === 'agent_build' ? '🛠️ ' : '🧩 ') + (m.text || '')));
    else box.appendChild(el('div', { class: 'ppme-text' }, m.text || ''));
    (m.proposals || []).forEach(function (p) { box.appendChild(proposalCard(p)); });
    chat.list.appendChild(box);
    chat.list.scrollTop = chat.list.scrollHeight;
  }
  /* ── Prochaine action : la « Prochaine étape » du Parcours, choisie par Stan ─────────
   * Stan lit tout le mémo, ses versions, vos échanges et le Parcours, choisit l'action qui
   * a le plus d'impact et la rattache à l'étape du Parcours qu'elle fait avancer.
   * « Faisons-le » la réalise ; « En faire un agent » la confie à un agent codé sur mesure,
   * rangé ensuite dans la Librairie. Les résultats arrivent dans l'onglet Chat. */
  var N = en ? {
    kicker: 'Next action · Stan', loading: 'Loading…',
    ask: 'Ask Stan for the best next action',
    askWhy: 'Stan reads the whole memo, its versions, your exchanges and this journey, then picks the action with the most impact now — and does it.',
    computing: 'Stan is studying the memo, its history and this journey… (1 to 3 min)',
    uncertainty: 'Key uncertainty', doIt: 'Let’s do it', asAgent: '🛠️ Make it an agent', other: 'Another idea',
    recompute: 'Recompute the next action', step: 'Moves forward: ', running: 'Stan is on it: ',
    done: function (t) { return 'Done: ' + t; }, see: 'See the result', nextOne: 'Next action',
    stale: function (n) { return 'Proposed on version ' + n + ': the memo has changed since.'; },
    types: { draft: '✉️ Ready-to-use draft', research: '🔎 Sourced research', memo: '📝 Memo update',
      agent: '🧩 Library agent', build_agent: '🛠️ Custom agent to code' },
    est: function (eur, min) { return '≈ ' + eur + ' € · ~' + min + ' min'; },
    asAgentWhy: function (eur) { return 'Stan codes an agent for this task, tries it on this deal (≈ ' + eur + ' €) and stores it in the Library for your next deals.'; },
    confirm: function (eur) { return 'Estimated cost: ' + eur + ' € (above 5 €). Go ahead?'; }, confirmBtn: 'Confirm', cancel: 'Cancel',
    copy: 'Copy', copied: 'Copied ✓', check: 'Check before use: ', impact: 'Impact on the decision: ', sources: 'Sources',
    signals: { 'continuer': 'Continue', 'à confirmer': 'To confirm', 'arrêter': 'Stop' }, failed: 'Stan could not finish: ',
    did: 'Let’s do it: ', didAgent: 'Make it an agent: ', alt: function (i, n) { return 'Alternative ' + i + ' of ' + n; },
    ready: function (t) { return '✅ ' + t + ': the result is in Chat.'; }, open: 'Open', started: 'Stan is on it — follow it in Parcours, the result will land in Chat.'
  } : {
    kicker: 'Prochaine action · Stan', loading: 'Chargement…',
    ask: 'Demander à Stan la meilleure prochaine action',
    askWhy: 'Stan lit tout le mémo, ses versions, vos échanges et ce Parcours, puis choisit l’action qui a le plus d’impact maintenant — et la réalise.',
    computing: 'Stan étudie le mémo, son historique et ce Parcours… (1 à 3 min)',
    uncertainty: 'Incertitude clé', doIt: 'Faisons-le', asAgent: '🛠️ En faire un agent', other: 'Autre idée',
    recompute: 'Recalculer la prochaine action', step: 'Fait avancer : ', running: 'Stan s’en occupe : ',
    done: function (t) { return 'Fait : ' + t; }, see: 'Voir le résultat', nextOne: 'Action suivante',
    stale: function (n) { return 'Proposée sur la version ' + n + ' : le mémo a changé depuis.'; },
    types: { draft: '✉️ Livrable prêt à l’emploi', research: '🔎 Recherche sourcée', memo: '📝 Mise à jour du mémo',
      agent: '🧩 Agent de la Librairie', build_agent: '🛠️ Agent sur mesure à coder' },
    est: function (eur, min) { return '≈ ' + eur + ' € · ~' + min + ' min'; },
    asAgentWhy: function (eur) { return 'Stan code un agent pour cette tâche, l’essaie sur ce dossier (≈ ' + eur + ' €) et le range dans la Librairie pour vos prochains dossiers.'; },
    confirm: function (eur) { return 'Coût estimé : ' + eur + ' € (au-delà de 5 €). On y va ?'; }, confirmBtn: 'Confirmer', cancel: 'Annuler',
    copy: 'Copier', copied: 'Copié ✓', check: 'À vérifier avant usage : ', impact: 'Ce que cela change pour la décision : ', sources: 'Sources',
    signals: { 'continuer': 'Continuer', 'à confirmer': 'À confirmer', 'arrêter': 'Arrêter' }, failed: 'Stan n’a pas pu terminer : ',
    did: 'Faisons-le : ', didAgent: 'En faire un agent : ', alt: function (i, n) { return 'Alternative ' + i + ' sur ' + n; },
    ready: function (t) { return '✅ ' + t + ' : le résultat est dans le Chat.'; }, open: 'Ouvrir', started: 'Stan s’en occupe : suivi dans le Parcours, résultat dans le Chat.'
  };
  var nba = { box: null, data: null, head: 0, index: 0, loaded: false, runs: {}, cost: 0, agentCost: 0, done: null };
  function fmtEur(x) {
    return Number(x || 0).toLocaleString(en ? 'en-GB' : 'fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  function highlight(node) {
    if (!node) return;
    node.scrollIntoView({ behavior: 'smooth', block: 'center' });
    node.classList.add('ppme-hl');
    setTimeout(function () { node.classList.remove('ppme-hl'); }, 3500);
  }
  // « [conviction#3] » dans un texte de Stan : un renvoi cliquable vers le bloc du mémo
  function citedText(text, tag, cls) {
    var node = el(tag, cls ? { class: cls } : {});
    String(text || '').split(/(\[[A-Za-z0-9][\w-]*#\d+\])/).forEach(function (part) {
      var m = /^\[([A-Za-z0-9][\w-]*)#(\d+)\]$/.exec(part);
      if (!m || !document.getElementById(m[1])) { node.appendChild(document.createTextNode(part)); return; }
      var b = el('button', { type: 'button', class: 'ppme-cite' }, sectionTitle(m[1]));
      b.onclick = function () { highlight(blockNode({ section: m[1], index: parseInt(m[2], 10) })); };
      node.appendChild(b);
    });
    return node;
  }
  function signalClass(s) { return s === 'continuer' ? 'go' : s === 'arrêter' ? 'stop' : 'wait'; }
  function nbaActions() {
    var n = nba.data && nba.data.nba;
    return n ? [n.action].concat(n.alternatives || []) : [];
  }
  function shown(node) { return !!node && node.offsetParent !== null; }
  function bar(buttons) {
    var row = el('div', { class: 'ppme-bar' });
    buttons.forEach(function (b) { if (b) row.appendChild(b); });
    return row;
  }
  function btn(label, onclick, cls, title) {
    var b = el('button', title ? { type: 'button', class: cls || '', title: title, 'aria-label': title } : { type: 'button', class: cls || '' }, label);
    b.onclick = function () { onclick(b); };
    return b;
  }
  function renderNba() {
    var box = nba.box;
    if (!box) return;
    box.innerHTML = '';
    var n = nba.data && nba.data.nba;
    box.classList.toggle('ppme-has-nba', !!n);          // elle prend la place de « Prochaine étape »
    box.appendChild(el('span', { class: 'ppme-kicker' }, '🎯 ' + N.kicker));
    var runs = Object.keys(nba.runs).map(function (k) { return nba.runs[k]; });
    runs.forEach(function (r) { if (r.op !== 'propose') box.appendChild(el('p', { class: 'ppme-nba-run' }, '⏳ ' + N.running + (r.title || ''))); });
    if (nba.done) {
      var done = el('div', { class: 'ppme-nba-done' });
      done.appendChild(el('span', {}, '✅ ' + N.done(nba.done.title)));
      done.appendChild(btn(N.see, function () { openStan('chat'); }));
      box.appendChild(done);
    }
    if (!nba.loaded) { box.appendChild(el('p', { class: 'ppme-wait' }, N.loading)); return; }
    if (runs.some(function (r) { return r.op === 'propose'; })) { box.appendChild(el('p', { class: 'ppme-wait' }, N.computing)); return; }
    if (!n) {
      box.appendChild(el('p', { class: 'ppme-why' }, N.askWhy));
      box.appendChild(bar([btn(N.ask + (nba.cost ? ' · ≈ ' + fmtEur(nba.cost) + ' €' : ''), proposeNext, 'ppme-go')]));
      return;
    }
    var acts = nbaActions(), i = nba.index % acts.length, a = acts[i];
    var meta = el('div', { class: 'ppme-nba-meta' });
    meta.appendChild(el('span', { class: 'ppme-chip' }, n.stage_label || n.stage));
    meta.appendChild(el('span', { class: 'ppme-chip sig-' + signalClass(n.signal), title: n.signal_reason || '' }, N.signals[n.signal] || n.signal));
    if (i) meta.appendChild(el('span', { class: 'ppme-chip' }, N.alt(i, acts.length - 1)));
    box.appendChild(meta);
    if (n.uncertainty && !i) {
      var u = citedText(n.uncertainty, 'p', 'ppme-unc');
      u.insertBefore(el('strong', {}, N.uncertainty + ' : '), u.firstChild);
      box.appendChild(u);
    }
    box.appendChild(el('span', { class: 'ppme-act-type' }, (N.types[a.type] || a.type) + (a.agent_name ? ' · ' + a.agent_name : '')));
    box.appendChild(el('strong', { class: 'ppme-act-title' }, a.title));
    if (a.why) box.appendChild(citedText(a.why, 'p', 'ppme-why'));
    var foot = el('p', { class: 'ppme-est' });
    if (a.parcours_step) {
      // l'étape du Parcours que cette action fait avancer : le Parcours l'ouvre (data-do="goto")
      foot.appendChild(el('button', { type: 'button', class: 'ppme-step', 'data-do': 'goto', 'data-id': a.parcours_step },
        N.step + (a.parcours_title || a.parcours_step) + ' →'));
      foot.appendChild(document.createTextNode(' · '));
    }
    foot.appendChild(document.createTextNode(N.est(fmtEur(a.est_eur), a.est_minutes || 5)));
    box.appendChild(foot);
    var head = Math.max(nba.head || 0, (state.head && state.head.n) || 0);
    if (nba.data.base && head > nba.data.base) box.appendChild(el('p', { class: 'ppme-stale' }, N.stale(nba.data.base)));
    var finished = nba.done && nba.done.action_id === a.id;
    var codable = ['draft', 'research', 'memo'].indexOf(a.type) >= 0;
    box.appendChild(bar([
      finished ? btn(N.nextOne + (nba.cost ? ' · ≈ ' + fmtEur(nba.cost) + ' €' : ''), proposeNext, 'ppme-go')
        : btn(N.doIt, function (b) { runAction(a, false, b, 'do'); }, 'ppme-go'),
      !finished && codable ? btn(N.asAgent, function (b) { runAction(a, false, b, 'agent'); }, '', N.asAgentWhy(fmtEur(nba.agentCost))) : null,
      acts.length > 1 ? btn(N.other, function () { nba.index++; renderNba(); }) : null,
      btn('↻', proposeNext, 'ppme-icon', N.recompute)
    ]));
  }
  function loadNext() {
    renderNba();
    api('/next').then(function (j) {
      nba.loaded = true;
      if (j.ok) {
        nba.data = j.cached || null;
        nba.head = j.head || 0;
        nba.cost = j.propose_eur || 0;
        nba.agentCost = j.build_eur || 0;
        (j.running || []).forEach(function (r) { track(r.run_id, r); });
      }
      renderNba();
    }).catch(function () { nba.loaded = true; renderNba(); });
  }
  function proposeNext() {
    nba.runs.pending = { op: 'propose' };
    nba.done = null;
    renderNba();
    api('/next', 'POST', {}).then(function (j) {
      delete nba.runs.pending;
      if (!j.ok) { renderNba(); toast(N.failed + (j.detail || j.error || j.status)); return; }
      track(j.run_id, { op: 'propose' });
    }).catch(function (e) { delete nba.runs.pending; renderNba(); toast(N.failed + e); });
  }
  // suit une exécution de fond jusqu'à son terme (le panneau peut être fermé et rouvert)
  function track(rid, info) {
    if (!rid || nba.runs[rid]) return;
    nba.runs[rid] = info;
    renderNba();
    var tries = 0;
    (function poll() {
      setTimeout(function () {
        api('/next/runs/' + rid).then(function (s) {
          if (s.state === 'running' && ++tries < 450) { poll(); return; }
          delete nba.runs[rid];
          if (s.state === 'done' && s.next) {
            nba.data = s.next; nba.index = 0; nba.done = null; nba.head = Math.max(nba.head, s.next.base || 0);
          } else if (s.state === 'done') {
            if (s.message && chat.loaded) renderMessage(s.message);
            nba.done = { title: info.title || '', action_id: info.action_id || '' };
            // la carte du Parcours ou le Chat le montrent déjà : sinon, on prévient
            if (!shown(nba.box) && !(chat.loaded && shown(chat.list))) {
              toast(N.ready(info.title || ''), [{ label: N.open, run: function () { openStan('chat'); } }]);
            }
            if (s.op === 'build' || s.op === 'agent') { lib.data = null; if (lib.box && !lib.box.hidden) loadLibrary(); }
          } else {
            toast(N.failed + (s.error || s.detail || s.status));
          }
          renderNba();
        }).catch(function () { if (++tries < 450) poll(); });
      }, tries < 20 ? 3000 : 8000);
    })();
  }
  function confirmIn(container, eur, onYes) {
    if (!container || container.querySelector('.ppme-confirm')) return;
    var box = el('div', { class: 'ppme-confirm', role: 'alertdialog' });
    box.appendChild(el('p', {}, N.confirm(fmtEur(eur))));
    box.appendChild(bar([btn(N.confirmBtn, function () { box.remove(); onYes(); }, 'ppme-go'),
                         btn(N.cancel, function () { box.remove(); })]));
    container.appendChild(box);
  }
  // « Faisons-le » (mode do) ou « En faire un agent » (mode agent) sur une action proposée
  function runAction(a, confirmed, button, mode) {
    if (button) button.disabled = true;
    api('/next/run', 'POST', { action_id: a.id, confirm: !!confirmed, mode: mode }).then(function (j) {
      if (button) button.disabled = false;
      if (j.needs_confirm) { confirmIn(nba.box, j.est_eur, function () { runAction(a, true, null, mode); }); return; }
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      if (chat.loaded) (j.messages || []).forEach(renderMessage);
      nba.done = null;
      track(j.run_id, { op: mode === 'agent' ? 'build' : a.type, title: a.title, action_id: a.id });
    }).catch(function (e) { if (button) button.disabled = false; toast(N.failed + e); });
  }
  function safeUrl(u) { return /^https?:\/\//i.test(String(u || '')) ? String(u) : ''; }
  function renderDeliverable(box, m) {
    box.appendChild(el('strong', {}, m.title || ''));
    box.appendChild(el('div', { class: 'ppme-text ppme-doc' }, m.text || ''));
    var copy = el('button', { type: 'button', class: 'ppme-link' }, N.copy);
    copy.onclick = function () {
      navigator.clipboard.writeText(m.text || '').then(function () { copy.textContent = N.copied; });
    };
    box.appendChild(copy);
    if (m.notes) box.appendChild(el('p', { class: 'ppme-why' }, N.check + m.notes));
  }
  function renderResearch(box, m, title) {
    var byN = {};
    (m.sources || []).forEach(function (s) { byN[s.n] = s; });
    if (title) box.appendChild(el('strong', {}, title));
    box.appendChild(el('div', { class: 'ppme-text' }, m.text || ''));
    var ul = el('ul', { class: 'ppme-findings' });
    (m.findings || []).forEach(function (f) {
      var li = el('li', {}, f.text);
      (f.sources || []).forEach(function (n) {
        var s = byN[n];
        if (!s || !safeUrl(s.url)) return;
        li.appendChild(document.createTextNode(' '));
        li.appendChild(el('a', { href: safeUrl(s.url), target: '_blank', rel: 'noopener noreferrer', class: 'ppme-src', title: s.title || s.url }, '[' + n + ']'));
      });
      ul.appendChild(li);
    });
    if ((m.findings || []).length) box.appendChild(ul);
    if (m.decision_impact) box.appendChild(el('p', { class: 'ppme-impact' }, N.impact + m.decision_impact));
    if ((m.sources || []).length) {
      var det = el('details', { class: 'ppme-sources' });
      det.appendChild(el('summary', {}, N.sources + ' (' + m.sources.length + ')'));
      var ol = el('ol', {});
      m.sources.forEach(function (s) {
        var li = el('li', {});
        if (safeUrl(s.url)) li.appendChild(el('a', { href: safeUrl(s.url), target: '_blank', rel: 'noopener noreferrer' }, s.title || s.url));
        ol.appendChild(li);
      });
      det.appendChild(ol);
      box.appendChild(det);
    }
  }
  /* ── Librairie : les agents que Stan a codés pour des prochaines actions ───────────
   * On ne les crée pas ici : ils naissent d'une prochaine action (« En faire un agent »,
   * ou un agent sur mesure proposé par Stan). Ici, on les relance, on les améliore ; leur
   * créateur les valide pour les partager avec tous les fonds. */
  var L = en ? {
    tab: 'Library', loading: 'Loading…',
    intro: 'The agents Stan coded for your next actions. Run them on this deal or improve them; once approved by their creator, they serve every fund. Each runs isolated, with no access to anything but the current deal.',
    empty: 'No agent yet. In Parcours, choose “🛠️ Make it an agent” on a next action: Stan codes it, tries it on this deal, and it lands here.',
    run: 'Run on this deal', code: 'View code', hideCode: 'Hide code',
    validate: 'Approve and share', improve: 'Improve', discard: 'Discard', retire: 'Remove from library',
    feedbackPh: 'What should be improved…', send: 'Send to Stan',
    shared: 'Shared with all funds', draft: 'Draft — visible to your fund', mine: 'created by you',
    uses: function (n) { return n + (n === 1 ? ' run' : ' runs'); }, pendingV: function (v) { return 'Version ' + v + ' awaiting approval'; },
    testOk: 'Trial on this deal succeeded', testKo: 'The trial failed: ',
    built: function (name, v) { return '🛠️ Agent coded: ' + name + ' (v' + v + ')'; },
    states: { shared: 'Shared with all funds', discarded: 'Discarded' },
    sharedToast: 'Agent shared with every fund.', discardedToast: 'Done.'
  } : {
    tab: 'Librairie', loading: 'Chargement…',
    intro: 'Les agents que Stan a codés pour vos prochaines actions. Relancez-les sur ce dossier ou améliorez-les ; validés par leur créateur, ils servent à tous les fonds. Chacun tourne isolé, sans accès à rien d’autre que le dossier en cours.',
    empty: 'Aucun agent pour l’instant. Dans le Parcours, choisissez « 🛠️ En faire un agent » sur une prochaine action : Stan le code, l’essaie sur ce dossier, et il arrive ici.',
    run: 'Lancer sur ce dossier', code: 'Voir le code', hideCode: 'Masquer le code',
    validate: 'Valider et partager', improve: 'Améliorer', discard: 'Abandonner', retire: 'Retirer de la librairie',
    feedbackPh: 'Ce qu’il faut améliorer…', send: 'Envoyer à Stan',
    shared: 'Partagé avec tous les fonds', draft: 'Brouillon — visible par votre fonds', mine: 'créé par vous',
    uses: function (n) { return n + (n > 1 ? ' utilisations' : ' utilisation'); }, pendingV: function (v) { return 'Version ' + v + ' à valider'; },
    testOk: 'Essai réussi sur ce dossier', testKo: 'L’essai a échoué : ',
    built: function (name, v) { return '🛠️ Agent codé : ' + name + ' (v' + v + ')'; },
    states: { shared: 'Partagé avec tous les fonds', discarded: 'Abandonné' },
    sharedToast: 'Agent partagé avec tous les fonds.', discardedToast: 'C’est fait.'
  };
  var lib = { box: null, data: null, state: {} };
  function loadLibrary() {
    if (!lib.box) return;
    if (!lib.data) { lib.box.innerHTML = ''; lib.box.appendChild(el('p', { class: 'ppme-wait' }, L.loading)); }
    api('/library').then(function (j) {
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      lib.data = j;
      renderLibrary();
    }).catch(function () {});
  }
  function renderLibrary() {
    var box = lib.box;
    if (!box || !lib.data) return;
    box.innerHTML = '';
    box.appendChild(el('p', { class: 'ppme-hint' }, L.intro));
    var agents = lib.data.agents || [];
    if (!agents.length) box.appendChild(el('p', { class: 'ppme-empty' }, L.empty));
    agents.forEach(function (a) { box.appendChild(agentCard(a)); });
  }
  function agentCard(a) {
    var card = el('div', { class: 'ppme-agent' });
    card.appendChild(el('strong', {}, a.name));
    if (a.description) card.appendChild(el('p', { class: 'ppme-why' }, a.description));
    var meta = [a.status === 'shared' ? L.shared : L.draft, 'v' + a.version, L.uses(a.uses), '≈ ' + fmtEur(a.est_eur) + ' €'];
    if (a.mine) meta.push(L.mine);
    card.appendChild(el('p', { class: 'ppme-est' }, meta.join(' · ')));
    if (a.mine && a.test && !a.test.ok && a.status === 'draft') card.appendChild(el('p', { class: 'ppme-stale' }, L.testKo + (a.test.error || '')));
    if (a.pending) {
      card.appendChild(el('p', { class: 'ppme-stale' }, L.pendingV(a.pending.version)
        + (a.pending.test && !a.pending.test.ok ? ' — ' + L.testKo + (a.pending.test.error || '') : '')));
    }
    var testOk = a.pending ? a.pending.test && a.pending.test.ok : a.status === 'draft' && a.test && a.test.ok;
    card.appendChild(bar([
      a.status === 'shared' || (a.test && a.test.ok) ? btn(L.run, function (b) { runAgent(a, false, b, card); }, 'ppme-go') : null,
      btn(L.code, function (b) { toggleCode(a, card, b); }),
      a.mine && testOk ? btn(L.validate, function (b) { agentDecision(a.id, 'validate', b); }) : null,
      btn(L.improve, function () { improveForm(a.id, card); }),
      a.mine ? btn(a.pending || a.status === 'draft' ? L.discard : L.retire, function (b) { agentDecision(a.id, 'discard', b); }) : null
    ]));
    return card;
  }
  function toggleCode(a, card, button) {
    var open = card.querySelector('.ppme-code');
    if (open) { open.remove(); button.textContent = L.code; return; }
    api('/agents/' + a.id).then(function (j) {
      if (!j.ok) { toast(N.failed + (j.detail || j.status)); return; }
      card.appendChild(el('pre', { class: 'ppme-code' }, j.pending_code || j.code || ''));
      button.textContent = L.hideCode;
    });
  }
  function improveForm(aid, container) {
    if (container.querySelector('.ppme-improve')) return;
    var form = el('div', { class: 'ppme-improve' });
    var text = el('textarea', { rows: '3', placeholder: L.feedbackPh, 'aria-label': L.improve });
    form.appendChild(text);
    form.appendChild(bar([btn(L.send, function (b) {
      if (text.value.trim().length < 5) { text.focus(); return; }
      b.disabled = true;
      buildAgent({ agent_id: aid, feedback: text.value.trim() }, function (ok) { b.disabled = false; if (ok) form.remove(); });
    }, 'ppme-go')]));
    container.appendChild(form);
    text.focus();
  }
  function launched(j, info) {
    if (chat.loaded) (j.messages || []).forEach(renderMessage);
    track(j.run_id, info);
    toast(N.started);
  }
  function buildAgent(body, done) {
    api('/agents/build', 'POST', body).then(function (j) {
      done(!!j.ok);
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      launched(j, { op: 'build', title: (j.messages && j.messages[0] && j.messages[0].text) || L.improve });
    }).catch(function (e) { done(false); toast(N.failed + e); });
  }
  function runAgent(a, confirmed, button, container) {
    if (button) button.disabled = true;
    api('/agents/' + a.id + '/run', 'POST', { confirm: !!confirmed }).then(function (j) {
      if (button) button.disabled = false;
      if (j.needs_confirm) { confirmIn(container, j.est_eur, function () { runAgent(a, true, null, container); }); return; }
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      launched(j, { op: 'agent', title: a.name });
    }).catch(function (e) { if (button) button.disabled = false; toast(N.failed + e); });
  }
  function agentDecision(aid, what, button) {
    if (button) button.disabled = true;
    api('/agents/' + aid + '/' + what, 'POST', {}).then(function (j) {
      if (button) button.disabled = false;
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      lib.state[aid] = what === 'validate' ? 'shared' : 'discarded';
      toast(what === 'validate' ? L.sharedToast : L.discardedToast);
      Array.prototype.forEach.call(document.querySelectorAll('.ppme-agent-acts[data-aid="' + aid + '"]'), function (n) {
        n.replaceWith(el('span', { class: 'ppme-status accepted' }, L.states[lib.state[aid]]));
      });
      lib.data = null;
      loadLibrary();
    }).catch(function (e) { if (button) button.disabled = false; toast(N.failed + e); });
  }
  function renderAgentDraft(box, m) {
    var a = m.agent || {};
    box.appendChild(el('strong', {}, L.built(a.name || '', a.version || 1)));
    if (a.description) box.appendChild(el('p', { class: 'ppme-why' }, a.description));
    if (m.error) box.appendChild(el('p', { class: 'ppme-stale' }, L.testKo + m.error));
    else {
      box.appendChild(el('p', { class: 'ppme-op-h' }, L.testOk));
      renderResearch(box, m, '');
      if (m.deliverable) renderDeliverable(box, { title: m.deliverable.title, text: m.deliverable.content });
    }
    if (lib.state[a.id]) { box.appendChild(el('span', { class: 'ppme-status accepted' }, L.states[lib.state[a.id]])); return; }
    var mine = a.by === state.email;
    var acts = bar([
      mine && a.ok ? btn(L.validate, function (b) { agentDecision(a.id, 'validate', b); }, 'ppme-go') : null,
      btn(L.improve, function () { improveForm(a.id, box); }),
      mine ? btn(L.discard, function (b) { agentDecision(a.id, 'discard', b); }) : null
    ]);
    acts.classList.add('ppme-agent-acts');
    acts.setAttribute('data-aid', a.id || '');
    box.appendChild(acts);
  }
  function renderAgentResult(box, m) {
    var a = m.agent || {};
    box.appendChild(el('strong', {}, '🧩 ' + (a.name || '')));
    if (m.error) { box.appendChild(el('p', { class: 'ppme-stale' }, N.failed + m.error)); return; }
    renderResearch(box, m, '');
    if (m.deliverable) renderDeliverable(box, { title: m.deliverable.title, text: m.deliverable.content });
  }
  /* ── Le poste de travail Stan (proplace-chat-memo.js) : Chat et Librairie en onglets à
   * côté du Parcours et de l'Historique ; la prochaine action dans la carte du Parcours. ── */
  function stan() {
    var SJ = window.StanJourney;
    return SJ && SJ.addView && SJ.addSlot && document.getElementById('stan-sidebar') ? SJ : null;
  }
  function whenStan(fn) {
    if (stan()) { fn(); return; }
    window.addEventListener('stan:ready', function () { if (stan()) fn(); }, { once: true });
  }
  function mountStan() {
    var SJ = stan();
    if (!SJ || chat.list) return;
    var box = SJ.addView('chat', C.tab, showChat);
    lib.box = SJ.addView('library', L.tab, loadLibrary);
    if (!box || !lib.box) return;
    lib.box.classList.add('ppme-lib');
    box.classList.add('ppme-chatview');
    box.appendChild(el('p', { class: 'ppme-hint' }, C.hint));
    chat.list = el('div', { class: 'ppme-msgs' });
    box.appendChild(chat.list);
    var form = el('form', { class: 'ppme-form' });
    var input = el('textarea', { rows: '3', placeholder: C.placeholder, 'aria-label': C.placeholder });
    var send = el('button', { type: 'submit', class: 'ppme-save' }, C.send);
    form.appendChild(input);
    form.appendChild(send);
    form.onsubmit = function (e) {
      e.preventDefault();
      var message = input.value.trim();
      if (!message || send.disabled) return;
      send.disabled = true;
      renderMessage({ type: 'message', role: 'user', by: state.email, at: new Date().toISOString(), text: message });
      input.value = '';
      var wait = el('div', { class: 'ppme-msg stan ppme-wait' }, C.thinking);
      chat.list.appendChild(wait);
      chat.list.scrollTop = chat.list.scrollHeight;
      api('/chat', 'POST', { message: message }).then(function (j) {
        wait.remove();
        send.disabled = false;
        if (!j.ok) { toast(T.error + (j.detail || j.error || j.status)); return; }
        (j.messages || []).slice(1).forEach(renderMessage);
      }).catch(function (err) { wait.remove(); send.disabled = false; toast(T.error + err); });
    };
    input.addEventListener('keydown', function (e) { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) form.requestSubmit(); });
    box.appendChild(form);
    chat.input = input;
    nba.box = el('section', { class: 'ppme-nba', 'aria-label': N.kicker });
    SJ.addSlot('next', nba.box);
    loadNext();
  }
  function showChat() {
    if (!chat.loaded) {
      chat.loaded = true;
      api('/chat').then(function (j) {
        if (!j.ok) { chat.loaded = false; return; }
        chat.list.innerHTML = '';
        (j.messages || []).forEach(function (m) {
          if (m.type === 'decision') chat.decisions[m.pid] = m.decision;
          if (m.type === 'agent_decision') lib.state[m.aid] = m.decision;
        });
        (j.messages || []).forEach(renderMessage);
      }).catch(function () { chat.loaded = false; });
    }
    chat.list.scrollTop = chat.list.scrollHeight;
    if (chat.input) chat.input.focus();
  }
  function openStan(view) {
    var SJ = stan();
    if (!SJ) return;
    mountStan();
    SJ.open(chat.list ? view : 'roadmap');
  }

  function buildPill() {
    if (document.querySelector('.ppme-pill')) return;
    var pill = el('div', { class: 'ppme-pill' });
    var talk = el('button', { type: 'button' }, C.chat);
    talk.onclick = function () { openStan('chat'); };
    pill.appendChild(talk);
    var edit = el('button', { type: 'button' }, T.editMemo);
    var versions = el('button', { type: 'button' }, T.versions);
    edit.onclick = function () {
      if (state.open) return;
      state.editing = !state.editing;
      edit.textContent = state.editing ? T.stopEdit : T.editMemo;
      decorate();
    };
    versions.onclick = openVersions;
    pill.appendChild(edit);
    pill.appendChild(versions);
    document.body.appendChild(pill);
  }
  function checkAccess() {
    if (state.role || !session()) return;
    api('/access').then(function (a) {
      if (!a.ok) return;
      state.role = a.role;
      state.email = a.email;
      if (a.head) state.head = a.head;
      injectCss();
      buildPill();
      decorate();
      whenStan(mountStan);
    }).catch(function () {});
  }
  function injectCss() {
    if (document.getElementById('ppme-css')) return;
    var css = el('style', { id: 'ppme-css' });
    css.textContent = [
      '.ppme-sec{position:relative}',
      '.ppme-edit{position:absolute;top:10px;right:10px;z-index:5;border:1px solid #BFE6CF;background:#EAF6EF;color:#0E6B37;border-radius:999px;padding:5px 12px;font-weight:600;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-edit:hover{background:#12A150;color:#fff;border-color:#12A150}',
      '.ppme-badge{display:inline-block;margin:4px 0 10px;padding:3px 10px;border-radius:999px;background:#FFF8E8;color:#7A5A00;font-size:12px}',
      '.ppme-editing{outline:2px solid #12A150;outline-offset:6px;border-radius:6px}',
      '.ppme-toolbar{position:sticky;top:8px;z-index:6;display:flex;gap:6px;align-items:center;margin:0 0 12px;padding:6px;background:#fff;border:1px solid #E3E8F0;border-radius:12px;box-shadow:0 6px 18px rgba(15,29,51,.12)}',
      '.ppme-toolbar button{border:1px solid #E3E8F0;background:#fff;border-radius:8px;min-width:32px;height:30px;padding:0 10px;font-weight:600;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-save{background:#12A150!important;color:#fff!important;border-color:#12A150!important;margin-left:auto}',
      '.ppme-pill{position:fixed;left:16px;bottom:16px;z-index:2147483000;display:flex;gap:6px;padding:6px;background:#fff;border:1px solid #E3E8F0;border-radius:999px;box-shadow:0 8px 24px rgba(15,29,51,.16)}',
      '.ppme-pill button{border:0;background:#F2F8F4;color:#0E6B37;border-radius:999px;padding:8px 14px;font-weight:700;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-toast,.ppme-preview{position:fixed;left:50%;transform:translateX(-50%);bottom:76px;z-index:2147483001;display:flex;gap:10px;align-items:center;max-width:min(680px,calc(100vw - 32px));padding:10px 14px;background:#16233A;color:#fff;border-radius:12px;font-size:13.5px;box-shadow:0 10px 30px rgba(15,29,51,.3)}',
      '.ppme-preview{top:16px;bottom:auto;background:#FFF8E8;color:#5C4400;border:1px solid #F3D08A}',
      '.ppme-toast button,.ppme-preview button{border:0;border-radius:999px;padding:6px 12px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer;background:#fff;color:#16233A}',
      '.ppme-x{background:none!important;color:inherit!important;font-size:18px!important;padding:0 4px!important}',
      '.ppme-modal{position:fixed;inset:0;z-index:2147483002;display:grid;place-items:center;background:rgba(15,29,51,.45);padding:16px}',
      '.ppme-card{width:min(640px,100%);max-height:80vh;overflow:auto;background:#fff;border-radius:16px;padding:18px 20px;color:#16233A}',
      '.ppme-card-h{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;font-size:16px}',
      '.ppme-list{list-style:none;margin:0;padding:0}',
      '.ppme-list li{display:flex;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #EEF2F7;font-size:13.5px}',
      '.ppme-n{font-weight:700;color:#0E6B37;min-width:34px}',
      '.ppme-what{flex:1;min-width:0}',
      '.ppme-cur{font-size:12px;color:#0E6B37;background:#EAF6EF;border-radius:999px;padding:2px 9px}',
      '.ppme-list button{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:5px 12px;font-weight:600;font-size:12.5px;font-family:inherit;cursor:pointer}',
      // le chat (onglet du poste de travail Stan)
      '.ppj-shell .ppme-chatview{overflow:hidden}',
      '.ppj-shell .ppme-hint{margin:0;font-size:12.5px;color:#61708A}',
      '.ppme-msgs{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:10px;padding:4px 2px}',
      '.ppme-msg{max-width:92%;padding:10px 12px;border-radius:12px;font-size:13.5px;line-height:1.5}',
      '.ppme-msg.me{align-self:flex-end;background:#EAF6EF}',
      '.ppme-msg.stan{align-self:flex-start;background:#fff;border:1px solid #E3E8F0}',
      '.ppme-who{font-size:11.5px;color:#61708A;margin-bottom:4px}',
      '.ppme-text{white-space:pre-wrap}',
      '.ppj-shell .ppme-wait{color:#61708A;font-style:italic;margin:0}',
      '.ppme-prop{margin-top:10px;padding:10px;border:1px solid #BFE6CF;border-radius:10px;background:#fff}',
      '.ppj-shell .ppme-why{margin:4px 0 8px;font-size:12.5px;color:#4B5E78}',
      '.ppme-op{margin:8px 0;padding-top:8px;border-top:1px dashed #E3E8F0}',
      '.ppj-shell .ppme-op-h{font-size:12px;font-weight:700;color:#0E6B37;margin:0 0 4px}',
      '.ppme-before{font-size:12.5px;color:#B42318;text-decoration:line-through;margin-bottom:4px}',
      '.ppme-after{font-size:12.5px;color:#0E6B37}',
      '.ppme-link{border:0;background:none;color:#3B4D66;text-decoration:underline;font-size:12px;padding:4px 0;cursor:pointer;font-family:inherit}',
      '.ppme-prop-actions{display:flex;gap:8px;margin-top:8px}',
      '.ppme-prop-actions button{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:6px 14px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-status{display:inline-block;margin-top:8px;font-size:12px;font-weight:700;border-radius:999px;padding:3px 10px}',
      '.ppme-status.accepted{background:#EAF6EF;color:#0E6B37}',
      '.ppme-status.declined{background:#EEF2F7;color:#61708A}',
      '.ppme-form{display:flex;gap:8px;align-items:flex-end}',
      '.ppj-shell .ppme-form textarea{flex:1;margin:0;resize:vertical;min-height:64px;border:1px solid #cbdcd2;border-radius:12px;padding:10px;font:13.5px system-ui}',
      '.ppme-form button{border:0;border-radius:999px;padding:10px 16px;font-weight:700;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-hl{outline:3px solid #E0A526!important;outline-offset:3px;background:#FFF8E8!important;transition:background .3s}',
      // résultats : livrables, constats sourcés, agents
      '.ppme-cite{border:0;background:#EEF2F7;color:#3B4D66;border-radius:6px;padding:0 6px;margin:0 1px;font-size:11.5px;font-family:inherit;cursor:pointer}',
      '.ppme-doc{background:#fff;border:1px solid #EEF2F7;border-radius:8px;padding:8px 10px;margin:6px 0;max-height:320px;overflow:auto}',
      '.ppme-findings{margin:6px 0;padding-left:18px}',
      '.ppj-shell .ppme-findings li{margin:4px 0;font-size:13px;line-height:1.45}',
      '.ppme-src{font-size:11.5px;color:#3B4D66}',
      '.ppj-shell .ppme-impact{font-size:12.5px;font-weight:600;margin:6px 0}',
      '.ppme-sources{font-size:12px;margin-top:6px}',
      '.ppj-shell .ppme-sources>summary{font-size:12.5px!important;font-weight:600;cursor:pointer}',
      '.ppme-sources ol{padding-left:18px;margin:4px 0}',
      '.ppj-shell .ppme-sources li{font-size:12px;margin:2px 0}',
      '.ppme-sources a{color:#3B4D66;word-break:break-word}',
      '.ppj-shell .ppme-est{font-size:12px;color:#61708A;margin:4px 0 0}',
      '.ppj-shell .ppme-stale{font-size:12px;color:#7A5A00;margin:8px 0 0}',
      '.ppme-bar{display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:10px}',
      '.ppme-bar button,.ppme-nba-done button{border:1px solid #d9e5dd;background:#fff;color:#294137;border-radius:999px;padding:7px 13px;font:700 12px/1.3 system-ui;cursor:pointer}',
      '.ppme-bar button:hover{background:#edf6f0}',
      '.ppme-bar .ppme-go{background:#12A150;color:#fff;border-color:#12A150}',
      '.ppme-bar .ppme-go:hover{background:#0E8A44}',
      '.ppme-bar button:disabled{opacity:.55;cursor:wait}',
      '.ppme-confirm{margin-top:10px;padding:10px;border-radius:10px;background:#FFF1D6;color:#5C4400}',
      '.ppj-shell .ppme-confirm p{margin:0}',
      // la librairie : les agents nés des prochaines actions
      '.ppme-lib .ppme-agent{padding:12px 14px;border:1px solid #dfe7e2;border-radius:12px;background:#fff;font-size:13px}',
      '.ppj-shell .ppme-empty{margin:0;padding:14px;border:1px dashed #cbdcd2;border-radius:12px;color:#536b60;font-size:13px}',
      '.ppme-code{max-height:300px;overflow:auto;margin:8px 0 0;padding:10px;background:#0F1D33;color:#E3E8F0;border-radius:10px;font-size:11.5px;line-height:1.45;white-space:pre}',
      '.ppme-improve{margin-top:8px}',
      '.ppj-shell .ppme-improve textarea{margin:0}',
      // la prochaine action de Stan, dans la carte « Objectif closing » du Parcours
      '.ppj-quest:has(.ppme-nba.ppme-has-nba) .ppj-next-cta{display:none}',
      '.ppme-nba{margin-top:14px;padding:12px 14px;border-radius:12px;background:#ffffff12;border:1px solid #ffffff2e;color:#fff;font-size:12.5px;line-height:1.45}',
      '.ppme-nba .ppme-kicker{display:block;margin-bottom:6px;font-size:10px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:#8FD8AF}',
      '.ppme-nba-meta{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:6px}',
      '.ppme-nba .ppme-chip{font-size:11px;font-weight:700;border-radius:999px;padding:2px 9px;background:#ffffff1f;color:#fff}',
      '.ppme-nba .ppme-chip.sig-go{background:#12A15055;color:#C9F5DA}',
      '.ppme-nba .ppme-chip.sig-wait{background:#E0A52655;color:#FFE6B0}',
      '.ppme-nba .ppme-chip.sig-stop{background:#E5484D55;color:#FFD0D2}',
      '.ppj-shell .ppj-quest .ppme-nba p{margin:0 0 6px}',
      '.ppj-shell .ppme-nba .ppme-unc,.ppj-shell .ppme-nba .ppme-why{color:#C5D4DF;font-size:12.5px}',
      '.ppme-nba .ppme-unc strong{color:#fff}',
      '.ppme-nba .ppme-act-type{display:block;font-size:11px;font-weight:700;color:#8FD8AF}',
      '.ppme-nba .ppme-act-title{display:block;margin:2px 0 4px;font-size:15px;line-height:1.3;color:#fff}',
      '.ppj-shell .ppme-nba .ppme-est{font-size:11.5px;color:#9FB3C2}',
      '.ppme-nba .ppme-step{border:0;background:none;padding:0;color:#8FD8AF;font:600 11.5px system-ui;text-decoration:underline;cursor:pointer;text-align:left}',
      '.ppj-shell .ppme-nba .ppme-stale{color:#FFE6B0}',
      '.ppj-shell .ppme-nba .ppme-wait{color:#C5D4DF}',
      '.ppme-nba .ppme-cite{background:#ffffff1f;color:#fff}',
      '.ppj-shell .ppme-nba-run{color:#C9F5DA;font-weight:600}',
      '.ppme-nba-done{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:0 0 8px;padding:8px 10px;border-radius:10px;background:#12A15033;color:#C9F5DA;font-weight:600}',
      '.ppme-nba .ppme-bar button,.ppme-nba-done button{border-color:#ffffff33;background:#ffffff14;color:#fff}',
      '.ppme-nba .ppme-bar button:hover,.ppme-nba-done button:hover{background:#ffffff26}',
      '.ppme-nba .ppme-bar .ppme-go{background:#12A150;border-color:#12A150;box-shadow:0 4px 14px #12A15055}',
      '.ppme-nba .ppme-icon{min-width:34px;padding:7px 10px}',
      '.ppme-nba .ppme-confirm{background:#ffffff1a;color:#fff}',
      // la pilule du mémo s'efface quand le panneau Stan couvre toute la page
      '@media (max-width:650px){body:has(#stan-sidebar:not([hidden])) .ppme-pill{display:none}.ppme-pill{left:12px;bottom:74px}.ppme-pill button{padding:7px 11px;font-size:12px}}',
      'body:has(#stan-sidebar.ppj-full:not([hidden])) .ppme-pill{display:none}'
    ].join('\n');
    document.head.appendChild(css);
  }

  syncLatest().then(checkAccess);
  // connexion faite dans le panneau Stan (cookie posé) : l'édition s'ouvre au retour
  window.addEventListener('focus', checkAccess);
  document.addEventListener('visibilitychange', function () { if (!document.hidden) checkAccess(); });
})();
