/* Mémo modifiable par l'équipe du fonds — versions privées (10/10/2026).
 *
 * Pour TOUT lecteur : si l'équipe a modifié le mémo depuis la publication statique,
 * la dernière version remplace le contenu de la page aussitôt (la page statique la
 * rattrape ~3 min plus tard).
 * Pour un membre de l'équipe du fonds connecté (session signée du code email) :
 * « Modifier » sur chaque section, badge « modifié par … », historique des versions
 * avec aperçu et restauration. Rien ne s'affiche pour les autres lecteurs.
 * Chargé par proplace-chat-memo.js (déjà présent sur toutes les pages de mémo).
 */
(function () {
  'use strict';
  if (window.PPMemoEditor) return;
  var meta = document.querySelector('meta[name="stan-deal"]');
  var area = document.querySelector('.content-area');
  if (!meta || !area) return;
  var ctx;
  try { ctx = JSON.parse(meta.content); } catch (_) { return; }
  var record = ctx.airtable_record || ctx.deal_id || '';
  if (!/^rec[a-zA-Z0-9]{10,30}$/.test(record)) return;
  var API = (window.__PP_MEMO_EDITS_API__ || 'https://alexandre-79537--memo-edits-fastapi-app.modal.run') + '/memos/' + record;
  var en = (document.documentElement.lang || 'fr').toLowerCase().indexOf('en') === 0;
  var T = en ? {
    edit: 'Edit', editMemo: '✏️ Edit the memo', stopEdit: '✓ Done editing', versions: '🕘 Versions', save: 'Save', cancel: 'Cancel',
    saved: function (n) { return 'Saved — version ' + n + '. The public page catches up in about 3 min.'; },
    conflict: function (by) { return 'The memo was changed by ' + by + ' in the meantime. Copy your text, then reload the latest version.'; },
    reload: 'Load the latest version', editedBy: function (who, when) { return 'Edited by ' + who + ' · ' + when; },
    viewing: function (n, when) { return 'You are viewing version ' + n + ' of ' + when + ' (read only).'; },
    restore: 'Restore this version', backToLatest: 'Back to the latest', show: 'View', current: 'current',
    restored: function (n) { return 'Version restored as version ' + n + '.'; }, close: 'Close', error: 'Could not save: ',
    kinds: { generated: 'Generated by Stan', edit: 'Edited by', stan: 'Proposed by Stan, approved by', restore: 'Restored by' },
    link: 'Link URL (https://…)', bold: 'Bold', italic: 'Italic', list: 'Bulleted list', linkBtn: 'Link',
    title: 'Memo versions', sections: 'sections'
  } : {
    edit: 'Modifier', editMemo: '✏️ Modifier le mémo', stopEdit: '✓ Terminer', versions: '🕘 Versions', save: 'Enregistrer', cancel: 'Annuler',
    saved: function (n) { return 'Enregistré — version ' + n + '. La page publique sera à jour dans ~3 min.'; },
    conflict: function (by) { return 'Le mémo a été modifié par ' + by + ' entre-temps. Copiez votre texte, puis rechargez la dernière version.'; },
    reload: 'Charger la dernière version', editedBy: function (who, when) { return 'Modifié par ' + who + ' · ' + when; },
    viewing: function (n, when) { return 'Vous regardez la version ' + n + ' du ' + when + ' (lecture seule).'; },
    restore: 'Restaurer cette version', backToLatest: 'Revenir à la dernière', show: 'Afficher', current: 'actuelle',
    restored: function (n) { return 'Version restaurée : c’est maintenant la version ' + n + '.'; }, close: 'Fermer', error: 'Enregistrement impossible : ',
    kinds: { generated: 'Générée par Stan', edit: 'Modifiée par', stan: 'Proposée par Stan, validée par', restore: 'Restaurée par' },
    link: 'Adresse du lien (https://…)', bold: 'Gras', italic: 'Italique', list: 'Liste à puces', linkBtn: 'Lien',
    title: 'Versions du mémo', sections: 'sections'
  };
  var state = { head: null, role: '', email: '', editing: false, open: null, preview: 0 };
  window.PPMemoEditor = { version: 3, state: state };

  function el(tag, attrs, text) {
    var node = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) { node.setAttribute(k, attrs[k]); });
    if (text != null) node.textContent = text;
    return node;
  }
  function session() {
    try {
      var cookie = document.cookie.split('; ').find(function (c) { return c.indexOf('proplace_auth=') === 0; });
      if (!cookie) return '';
      var auth = JSON.parse(atob(decodeURIComponent(cookie.slice('proplace_auth='.length))));
      return auth && typeof auth.member_session === 'string' ? auth.member_session : '';
    } catch (_) { return ''; }
  }
  function api(path, method, body) {
    var headers = { 'Content-Type': 'application/json' };
    var s = session();
    if (s) headers['X-Member-Session'] = s;
    return fetch(API + path, { method: method || 'GET', headers: headers, credentials: 'omit',
      body: body ? JSON.stringify(body) : undefined })
      .then(function (r) { return r.json().catch(function () { return {}; }).then(function (j) { j.status = r.status; return j; }); });
  }
  function pageVersion() {
    var m = document.querySelector('meta[name="pp-memo-version"]');
    return m ? parseInt(m.getAttribute('content'), 10) || 0 : 0;
  }
  function setPageVersion(n) {
    var m = document.querySelector('meta[name="pp-memo-version"]');
    if (!m) { m = el('meta', { name: 'pp-memo-version' }); document.head.appendChild(m); }
    m.setAttribute('content', String(n));
  }
  function when(iso) {
    var d = new Date(iso || '');
    if (isNaN(d.getTime())) return '';
    return d.toLocaleString(en ? 'en-GB' : 'fr-FR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' });
  }
  function shortWho(email) { return String(email || '').split('@')[0] || 'Stan'; }
  function sections() { return Array.prototype.slice.call(area.querySelectorAll('.section-container[id]')); }
  function toast(text, actions) {
    var old = document.querySelector('.ppme-toast');
    if (old) old.remove();
    var box = el('div', { class: 'ppme-toast', role: 'status' });
    box.appendChild(el('span', {}, text));
    (actions || []).forEach(function (a) {
      var b = el('button', { type: 'button' }, a.label);
      b.onclick = function () { box.remove(); a.run(); };
      box.appendChild(b);
    });
    var x = el('button', { type: 'button', class: 'ppme-x', 'aria-label': T.close }, '×');
    x.onclick = function () { box.remove(); };
    box.appendChild(x);
    document.body.appendChild(box);
    if (!actions) setTimeout(function () { box.remove(); }, 7000);
  }

  /* ── la dernière version pour tout lecteur ─────────────────────────────── */
  function swapArea(html) {
    area.innerHTML = html;
    // des scripts insérés par innerHTML ne s'exécutent pas : on les rejoue (graphiques, plan d'action)
    Array.prototype.forEach.call(area.querySelectorAll('script'), function (old) {
      var s = document.createElement('script');
      Array.prototype.forEach.call(old.attributes, function (a) { s.setAttribute(a.name, a.value); });
      s.text = old.text;
      old.parentNode.replaceChild(s, old);
    });
  }
  function loadVersion(n, asHead) {
    return api('/content' + (asHead ? '' : '?n=' + n)).then(function (c) {
      if (!c.ok || !c.content_area) return null;
      swapArea(c.content_area);
      if (asHead) setPageVersion(c.n);
      decorate();
      return c;
    });
  }
  function syncLatest() {
    return api('/head').then(function (h) {
      if (!h.ok) return;
      state.head = h;
      var mine = pageVersion();
      if (mine ? mine < h.n : h.edited) return loadVersion(h.n, true);
    }).catch(function () {});
  }

  /* ── l'équipe du fonds : modifier, badges, versions ─────────────────────── */
  function decorate() {
    sections().forEach(function (sec) {
      Array.prototype.forEach.call(sec.querySelectorAll(':scope > .ppme-ui'), function (n) { n.remove(); });
      if (!state.role || state.preview) return;
      sec.classList.add('ppme-sec');
      var by = sec.getAttribute('data-pp-edited-by');
      if (by) {
        var badge = el('div', { class: 'ppme-ui ppme-badge' }, T.editedBy(shortWho(by), when(sec.getAttribute('data-pp-edited-at'))));
        var title = sec.querySelector(':scope > h2, :scope > .section-title');
        if (title && title.nextSibling) sec.insertBefore(badge, title.nextSibling); else sec.insertBefore(badge, sec.firstChild);
      }
      if (state.editing) {
        var btn = el('button', { type: 'button', class: 'ppme-ui ppme-edit' }, '✏️ ' + T.edit);
        btn.onclick = function () { startEdit(sec); };
        sec.insertBefore(btn, sec.firstChild);
      }
    });
  }
  function cleanHtml(sec) {
    var clone = sec.cloneNode(true);
    Array.prototype.forEach.call(clone.querySelectorAll('.ppme-ui'), function (n) { n.remove(); });
    return clone.innerHTML;
  }
  function startEdit(sec) {
    if (state.open) return;
    Array.prototype.forEach.call(sec.querySelectorAll(':scope > .ppme-ui'), function (n) { n.remove(); });
    state.open = { sec: sec, before: sec.innerHTML };
    sec.classList.add('ppme-editing');
    var bar = el('div', { class: 'ppme-ui ppme-toolbar', contenteditable: 'false' });
    [['bold', 'B', T.bold], ['italic', 'I', T.italic], ['insertUnorderedList', '•', T.list], ['createLink', '🔗', T.linkBtn]]
      .forEach(function (c) {
        var b = el('button', { type: 'button', title: c[2], 'aria-label': c[2] }, c[1]);
        b.onmousedown = function (e) { e.preventDefault(); };
        b.onclick = function () {
          if (c[0] === 'createLink') {
            var url = window.prompt(T.link, 'https://');
            if (url && /^https?:\/\//i.test(url)) document.execCommand('createLink', false, url);
          } else document.execCommand(c[0], false, null);
        };
        bar.appendChild(b);
      });
    var save = el('button', { type: 'button', class: 'ppme-save' }, T.save);
    var cancel = el('button', { type: 'button', class: 'ppme-cancel' }, T.cancel);
    save.onclick = saveEdit;
    cancel.onclick = cancelEdit;
    bar.appendChild(save);
    bar.appendChild(cancel);
    sec.insertBefore(bar, sec.firstChild);
    sec.setAttribute('contenteditable', 'true');
    sec.focus();
  }
  function closeEdit() {
    var sec = state.open.sec;
    sec.removeAttribute('contenteditable');
    sec.classList.remove('ppme-editing');
    state.open = null;
  }
  function cancelEdit() {
    var sec = state.open.sec;
    sec.innerHTML = state.open.before;
    closeEdit();
    decorate();
  }
  function saveEdit() {
    var sec = state.open.sec;
    var html = cleanHtml(sec);
    var base = pageVersion() || (state.head && state.head.n) || 0;
    api('/edit', 'POST', { base: base, section_id: sec.id, html: html }).then(function (j) {
      if (j.ok) {
        closeEdit();
        setPageVersion(j.n);
        state.head = j;
        sec.setAttribute('data-pp-edited-by', state.email);
        sec.setAttribute('data-pp-edited-at', j.at || '');
        decorate();
        toast(T.saved(j.n));
      } else if (j.status === 409 && j.head) {
        toast(T.conflict(shortWho(j.head.by)), [{ label: T.reload, run: function () {
          closeEdit(); loadVersion(j.head.n, true);
        } }]);
      } else {
        toast(T.error + (j.detail || j.error || j.status));
      }
    }).catch(function (e) { toast(T.error + e); });
  }
  function kindLabel(v) {
    var k = T.kinds[v.kind] || v.kind;
    return v.kind === 'generated' ? k : k + ' ' + shortWho(v.by);
  }
  function openVersions() {
    api('/versions').then(function (j) {
      if (!j.ok) { toast(T.error + (j.detail || j.status)); return; }
      var old = document.querySelector('.ppme-modal');
      if (old) old.remove();
      var modal = el('div', { class: 'ppme-modal', role: 'dialog', 'aria-modal': 'true', 'aria-label': T.title });
      var card = el('div', { class: 'ppme-card' });
      var head = el('div', { class: 'ppme-card-h' });
      head.appendChild(el('strong', {}, T.title));
      var x = el('button', { type: 'button', class: 'ppme-x', 'aria-label': T.close }, '×');
      x.onclick = function () { modal.remove(); };
      head.appendChild(x);
      card.appendChild(head);
      var list = el('ol', { class: 'ppme-list' });
      (j.versions || []).forEach(function (v, i) {
        var li = el('li');
        li.appendChild(el('span', { class: 'ppme-n' }, 'v' + v.n));
        var titles = (v.sections || []).map(function (id) {
          var t = document.querySelector('#' + CSS.escape(id) + ' .section-title, #' + CSS.escape(id) + ' h2');
          return t ? t.textContent.trim() : id;
        });
        var text = el('span', { class: 'ppme-what' }, kindLabel(v) + ' · ' + when(v.at)
          + (titles.length ? ' · ' + titles.join(', ') : '') + (v.note ? ' — ' + v.note : ''));
        li.appendChild(text);
        if (i === 0) li.appendChild(el('span', { class: 'ppme-cur' }, T.current));
        else {
          var show = el('button', { type: 'button' }, T.show);
          show.onclick = function () { modal.remove(); preview(v); };
          li.appendChild(show);
        }
        list.appendChild(li);
      });
      card.appendChild(list);
      modal.appendChild(card);
      modal.onclick = function (e) { if (e.target === modal) modal.remove(); };
      document.body.appendChild(modal);
    });
  }
  function preview(v) {
    loadVersion(v.n, false).then(function (c) {
      if (!c) return;
      state.preview = v.n;
      decorate();
      var bar = el('div', { class: 'ppme-preview', role: 'status' });
      bar.appendChild(el('span', {}, T.viewing(v.n, when(v.at))));
      var restore = el('button', { type: 'button', class: 'ppme-save' }, T.restore);
      var back = el('button', { type: 'button' }, T.backToLatest);
      restore.onclick = function () {
        api('/restore', 'POST', { base: state.head ? state.head.n : 0, n: v.n }).then(function (j) {
          bar.remove(); state.preview = 0;
          if (j.ok) { state.head = j; loadVersion(j.n, true).then(function () { toast(T.restored(j.n)); }); }
          else if (j.status === 409 && j.head) { loadVersion(j.head.n, true); toast(T.conflict(shortWho(j.head.by))); }
          else toast(T.error + (j.detail || j.error || j.status));
        });
      };
      back.onclick = function () { bar.remove(); state.preview = 0; loadVersion(0, true); };
      bar.appendChild(restore);
      bar.appendChild(back);
      document.body.appendChild(bar);
    });
  }
  /* ── Stan chat : réponses et modifications proposées, validées par l'équipe ── */
  var BLOCKS = 'p, li, h3, h4, tr, blockquote, figcaption';
  var C = en ? {
    chat: '💬 Stan', title: 'Stan · Chat', hint: 'Ask anything about this deal. When a change to the memo is useful, Stan proposes it — you approve.',
    placeholder: 'e.g. “Rewrite the verdict with what we learned on the call: the CEO wants to sell in 2027”',
    send: 'Send', thinking: 'Stan is thinking…', accept: 'Accept', decline: 'Decline', view: 'Show in memo',
    accepted: 'Accepted', declined: 'Declined', applied: function (n) { return 'Stan’s change applied — version ' + n + '.'; },
    actions: { replace: 'Rewrite', insert_after: 'Add after', 'delete': 'Remove' }, you: 'You', cost: 'cost'
  } : {
    chat: '💬 Stan', title: 'Stan · Chat', hint: 'Demandez n’importe quoi sur ce dossier. Quand une modification du mémo est utile, Stan la propose — vous validez.',
    placeholder: 'ex. « Réécris le verdict avec ce qu’on a appris à l’appel : le dirigeant veut céder en 2027 »',
    send: 'Envoyer', thinking: 'Stan réfléchit…', accept: 'Accepter', decline: 'Refuser', view: 'Voir dans le mémo',
    accepted: 'Acceptée', declined: 'Refusée', applied: function (n) { return 'Modification de Stan appliquée — version ' + n + '.'; },
    actions: { replace: 'Réécrire', insert_after: 'Ajouter après', 'delete': 'Retirer' }, you: 'Vous', cost: 'coût'
  };
  var chat = { panel: null, list: null, decisions: {} };
  function sectionTitle(id) {
    var t = document.querySelector('#' + CSS.escape(id) + ' .section-title, #' + CSS.escape(id) + ' h2');
    return t ? t.textContent.trim() : id;
  }
  function blockNode(op) {
    var sec = document.getElementById(op.section);
    if (!sec) return null;
    var nodes = Array.prototype.filter.call(sec.querySelectorAll(BLOCKS), function (n) { return !n.closest('.ppme-ui'); });
    return nodes[op.index] || null;
  }
  function plain(html) { var d = document.createElement('div'); d.innerHTML = html || ''; return d.textContent.trim(); }
  function proposalCard(prop) {
    var card = el('div', { class: 'ppme-prop' });
    card.appendChild(el('strong', {}, prop.title || 'Proposition'));
    if (prop.why) card.appendChild(el('p', { class: 'ppme-why' }, prop.why));
    (prop.ops || []).forEach(function (op) {
      var row = el('div', { class: 'ppme-op' });
      row.appendChild(el('div', { class: 'ppme-op-h' }, (C.actions[op.action] || op.action) + ' · ' + sectionTitle(op.section)));
      if (op.action !== 'insert_after' && op.before) row.appendChild(el('div', { class: 'ppme-before' }, op.before));
      if (op.action !== 'delete') row.appendChild(el('div', { class: 'ppme-after' }, plain(op.html)));
      var view = el('button', { type: 'button', class: 'ppme-link' }, C.view);
      view.onclick = function () { highlight(blockNode(op)); };
      row.appendChild(view);
      card.appendChild(row);
    });
    var status = chat.decisions[prop.id];
    if (status) {
      card.appendChild(el('span', { class: 'ppme-status ' + status }, status === 'accepted' ? C.accepted : C.declined));
      return card;
    }
    var bar = el('div', { class: 'ppme-prop-actions' });
    var ok = el('button', { type: 'button', class: 'ppme-save' }, C.accept);
    var no = el('button', { type: 'button' }, C.decline);
    ok.onclick = function () {
      ok.disabled = no.disabled = true;
      api('/proposals/' + prop.id + '/accept', 'POST', { base: pageVersion() || (state.head && state.head.n) || 0 }).then(function (j) {
        if (j.ok) {
          chat.decisions[prop.id] = 'accepted';
          state.head = j;
          loadVersion(j.n, true).then(function () { toast(C.applied(j.n)); });
          card.replaceWith(proposalCard(prop));
          renderNba();
        } else {
          ok.disabled = no.disabled = false;
          toast(T.error + (j.detail || j.error || j.status));
        }
      });
    };
    no.onclick = function () {
      api('/proposals/' + prop.id + '/decline', 'POST', {}).then(function () {
        chat.decisions[prop.id] = 'declined';
        card.replaceWith(proposalCard(prop));
      });
    };
    bar.appendChild(ok);
    bar.appendChild(no);
    card.appendChild(bar);
    return card;
  }
  function renderMessage(m) {
    if (m.type !== 'message' || !chat.list) return;
    var mine = m.role === 'user';
    var box = el('div', { class: 'ppme-msg ' + (mine ? 'me' : 'stan') + (m.kind ? ' ppme-' + m.kind : '') });
    box.appendChild(el('div', { class: 'ppme-who' }, (mine ? (m.by === state.email ? C.you : shortWho(m.by)) : 'Stan') + ' · ' + when(m.at)
      + (!mine && m.cost ? ' · ' + C.cost + ' ' + Number(m.cost).toFixed(2) + ' $' : '')
      + (!mine && m.cost_eur ? ' · ' + C.cost + ' ' + fmtEur(m.cost_eur) + ' €' : '')));
    if (m.kind === 'deliverable') renderDeliverable(box, m);
    else if (m.kind === 'research') renderResearch(box, m, m.action && m.action.title);
    else if (m.kind === 'agent_draft') renderAgentDraft(box, m);
    else if (m.kind === 'agent_result') renderAgentResult(box, m);
    else if (m.kind === 'next_action') box.appendChild(el('div', { class: 'ppme-text' }, '🎯 ' + N.did + ((m.action && m.action.title) || m.text || '')));
    else if (m.kind === 'agent_build' || m.kind === 'agent_run') box.appendChild(el('div', { class: 'ppme-text' }, (m.kind === 'agent_build' ? '🛠️ ' : '🧩 ') + (m.text || '')));
    else box.appendChild(el('div', { class: 'ppme-text' }, m.text || ''));
    (m.proposals || []).forEach(function (p) { box.appendChild(proposalCard(p)); });
    chat.list.appendChild(box);
    chat.list.scrollTop = chat.list.scrollHeight;
  }
  /* ── Prochaine action : la plus utile maintenant, réalisée par Stan sur « Faisons-le » ── */
  var N = en ? {
    title: '🎯 Next best action', loading: 'Loading…',
    empty: 'Stan reads the whole memo, its versions, your exchanges and the deal progress, then proposes the single action with the most impact now — and does it.',
    propose: 'Propose the next action', computing: 'Stan is studying the memo, its history and the deal progress… (1 to 3 min)',
    uncertainty: 'Key uncertainty', doIt: 'Let’s do it', other: 'Another idea', recompute: 'Recompute',
    running: 'In progress: ', stale: function (n) { return 'Proposed on version ' + n + ': the memo has changed since.'; },
    types: { draft: '✉️ Ready-to-use draft', research: '🔎 Sourced research', memo: '📝 Memo update',
      agent: '🧩 Library agent', build_agent: '🛠️ Code a custom agent' },
    est: function (eur, min) { return 'Estimated cost ≈ ' + eur + ' € · ~' + min + ' min'; },
    confirm: function (eur) { return 'Estimated cost: ' + eur + ' € (above 5 €). Go ahead?'; }, confirmBtn: 'Confirm', cancel: 'Cancel',
    copy: 'Copy', copied: 'Copied ✓', check: 'Check before use: ', impact: 'Impact on the decision: ', sources: 'Sources',
    signals: { 'continuer': 'Continue', 'à confirmer': 'To confirm', 'arrêter': 'Stop' }, failed: 'Stan could not finish: ',
    did: 'Let’s do it: ', alt: function (i, n) { return 'Alternative ' + i + ' of ' + n; }, deliverable: 'Deliverable: ', fold: 'Show or hide'
  } : {
    title: '🎯 Prochaine action', loading: 'Chargement…',
    empty: 'Stan lit tout le mémo, ses versions, vos échanges et l’avancement du Parcours, puis propose LA prochaine action qui a le plus d’impact — et la réalise.',
    propose: 'Proposer la prochaine action', computing: 'Stan étudie le mémo, son historique et le Parcours… (1 à 3 min)',
    uncertainty: 'Incertitude clé', doIt: 'Faisons-le', other: 'Autre idée', recompute: 'Recalculer',
    running: 'En cours : ', stale: function (n) { return 'Proposée sur la version ' + n + ' : le mémo a changé depuis.'; },
    types: { draft: '✉️ Livrable prêt à l’emploi', research: '🔎 Recherche sourcée', memo: '📝 Mise à jour du mémo',
      agent: '🧩 Agent de la librairie', build_agent: '🛠️ Coder un agent sur mesure' },
    est: function (eur, min) { return 'Coût estimé ≈ ' + eur + ' € · ~' + min + ' min'; },
    confirm: function (eur) { return 'Coût estimé : ' + eur + ' € (au-delà de 5 €). On y va ?'; }, confirmBtn: 'Confirmer', cancel: 'Annuler',
    copy: 'Copier', copied: 'Copié ✓', check: 'À vérifier avant usage : ', impact: 'Ce que cela change pour la décision : ', sources: 'Sources',
    signals: { 'continuer': 'Continuer', 'à confirmer': 'À confirmer', 'arrêter': 'Arrêter' }, failed: 'Stan n’a pas pu terminer : ',
    did: 'Faisons-le : ', alt: function (i, n) { return 'Alternative ' + i + ' sur ' + n; }, deliverable: 'Livrable : ', fold: 'Afficher ou masquer'
  };
  var nba = { box: null, data: null, head: 0, index: 0, loaded: false, runs: {}, folded: false, cost: 0 };
  try { nba.folded = localStorage.getItem('ppme-nba-folded') === '1'; } catch (_) {}
  function fmtEur(x) {
    return Number(x || 0).toLocaleString(en ? 'en-GB' : 'fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  function highlight(node) {
    if (!node) return;
    node.scrollIntoView({ behavior: 'smooth', block: 'center' });
    node.classList.add('ppme-hl');
    setTimeout(function () { node.classList.remove('ppme-hl'); }, 3500);
  }
  // « [conviction#3] » dans un texte de Stan : un renvoi cliquable vers le bloc du mémo
  function citedText(text, tag, cls) {
    var node = el(tag, cls ? { class: cls } : {});
    String(text || '').split(/(\[[A-Za-z0-9][\w-]*#\d+\])/).forEach(function (part) {
      var m = /^\[([A-Za-z0-9][\w-]*)#(\d+)\]$/.exec(part);
      if (!m || !document.getElementById(m[1])) { node.appendChild(document.createTextNode(part)); return; }
      var b = el('button', { type: 'button', class: 'ppme-cite' }, sectionTitle(m[1]));
      b.onclick = function () { highlight(blockNode({ section: m[1], index: parseInt(m[2], 10) })); };
      node.appendChild(b);
    });
    return node;
  }
  function signalClass(s) { return s === 'continuer' ? 'go' : s === 'arrêter' ? 'stop' : 'wait'; }
  function nbaActions() {
    var n = nba.data && nba.data.nba;
    return n ? [n.action].concat(n.alternatives || []) : [];
  }
  function renderNba() {
    var box = nba.box;
    if (!box) return;
    box.innerHTML = '';
    var h = el('button', { type: 'button', class: 'ppme-nba-h', 'aria-expanded': String(!nba.folded), title: N.fold },
      (nba.folded ? '▸ ' : '▾ ') + N.title);
    h.onclick = function () {
      nba.folded = !nba.folded;
      try { localStorage.setItem('ppme-nba-folded', nba.folded ? '1' : '0'); } catch (_) {}
      renderNba();
    };
    box.appendChild(h);
    if (nba.folded) {
      var cur = nbaActions()[nba.index % (nbaActions().length || 1)];
      if (cur) box.appendChild(el('div', { class: 'ppme-nba-folded' }, cur.title));
      return;
    }
    var runs = Object.keys(nba.runs).map(function (k) { return nba.runs[k]; });
    runs.forEach(function (r) { if (r.op !== 'propose') box.appendChild(el('div', { class: 'ppme-nba-run' }, N.running + (r.title || ''))); });
    if (!nba.loaded) { box.appendChild(el('div', { class: 'ppme-wait' }, N.loading)); return; }
    if (runs.some(function (r) { return r.op === 'propose'; })) { box.appendChild(el('div', { class: 'ppme-wait' }, N.computing)); return; }
    var n = nba.data && nba.data.nba;
    if (!n) {
      box.appendChild(el('p', { class: 'ppme-why' }, N.empty));
      var first = el('button', { type: 'button', class: 'ppme-go' }, N.propose + (nba.cost ? ' · ≈ ' + fmtEur(nba.cost) + ' €' : ''));
      first.onclick = proposeNext;
      box.appendChild(first);
      return;
    }
    var acts = nbaActions();
    var i = nba.index % acts.length;
    var a = acts[i];
    var meta = el('div', { class: 'ppme-nba-meta' });
    meta.appendChild(el('span', { class: 'ppme-chip' }, n.stage_label || n.stage));
    meta.appendChild(el('span', { class: 'ppme-chip sig-' + signalClass(n.signal) }, N.signals[n.signal] || n.signal));
    box.appendChild(meta);
    if (n.signal_reason) box.appendChild(citedText(n.signal_reason, 'p', 'ppme-why'));
    if (n.uncertainty) {
      var u = citedText(n.uncertainty, 'p', 'ppme-unc');
      u.insertBefore(el('strong', {}, N.uncertainty + ' : '), u.firstChild);
      box.appendChild(u);
    }
    var act = el('div', { class: 'ppme-nba-act' });
    act.appendChild(el('div', { class: 'ppme-op-h' }, (i ? N.alt(i, acts.length - 1) + ' · ' : '') + (N.types[a.type] || a.type)
      + (a.agent_name ? ' · ' + a.agent_name : '')));
    act.appendChild(el('strong', {}, a.title));
    if (a.why) act.appendChild(citedText(a.why, 'p', 'ppme-why'));
    if (a.deliverable) act.appendChild(citedText(N.deliverable + a.deliverable, 'p', 'ppme-why'));
    act.appendChild(el('div', { class: 'ppme-est' }, N.est(fmtEur(a.est_eur), a.est_minutes || 5)));
    box.appendChild(act);
    var head = Math.max(nba.head || 0, (state.head && state.head.n) || 0);
    if (nba.data.base && head > nba.data.base) box.appendChild(el('p', { class: 'ppme-stale' }, N.stale(nba.data.base)));
    var bar = el('div', { class: 'ppme-nba-bar' });
    var go = el('button', { type: 'button', class: 'ppme-go' }, N.doIt);
    go.onclick = function () { runAction(a, false, go); };
    bar.appendChild(go);
    if (acts.length > 1) {
      var other = el('button', { type: 'button' }, N.other);
      other.onclick = function () { nba.index++; renderNba(); };
      bar.appendChild(other);
    }
    var again = el('button', { type: 'button', title: nba.cost ? '≈ ' + fmtEur(nba.cost) + ' €' : '' }, N.recompute);
    again.onclick = proposeNext;
    bar.appendChild(again);
    box.appendChild(bar);
  }
  function loadNext() {
    renderNba();
    api('/next').then(function (j) {
      if (!j.ok) { if (nba.box) nba.box.remove(); nba.box = null; return; }
      nba.data = j.cached || null;
      nba.head = j.head || 0;
      nba.cost = j.propose_eur || 0;
      nba.loaded = true;
      (j.running || []).forEach(function (r) { track(r.run_id, r); });
      renderNba();
    }).catch(function () {});
  }
  function proposeNext() {
    nba.runs.pending = { op: 'propose' };
    renderNba();
    api('/next', 'POST', {}).then(function (j) {
      delete nba.runs.pending;
      if (!j.ok) { renderNba(); toast(N.failed + (j.detail || j.error || j.status)); return; }
      track(j.run_id, { op: 'propose' });
    }).catch(function (e) { delete nba.runs.pending; renderNba(); toast(N.failed + e); });
  }
  // suit une exécution de fond jusqu'à son terme (le panneau peut être fermé et rouvert)
  function track(rid, info) {
    if (!rid || nba.runs[rid]) return;
    nba.runs[rid] = info;
    renderNba();
    var tries = 0;
    (function poll() {
      setTimeout(function () {
        api('/next/runs/' + rid).then(function (s) {
          if (s.state === 'running' && ++tries < 450) { poll(); return; }
          delete nba.runs[rid];
          if (s.state === 'done') {
            if (s.next) { nba.data = s.next; nba.index = 0; nba.head = Math.max(nba.head, s.next.base || 0); }
            if (s.message && chat.panel) renderMessage(s.message);
            if (s.op === 'build' || s.op === 'agent') lib.data = null;
          } else {
            toast(N.failed + (s.error || s.detail || s.status));
          }
          renderNba();
        }).catch(function () { if (++tries < 450) poll(); });
      }, tries < 20 ? 3000 : 8000);
    })();
  }
  function runAction(a, confirmed, btn) {
    if (btn) btn.disabled = true;
    api('/next/run', 'POST', { action_id: a.id, confirm: !!confirmed }).then(function (j) {
      if (btn) btn.disabled = false;
      if (j.needs_confirm) { askConfirm(a, j.est_eur); return; }
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      (j.messages || []).forEach(renderMessage);
      track(j.run_id, { op: a.type, title: a.title });
    }).catch(function (e) { if (btn) btn.disabled = false; toast(N.failed + e); });
  }
  function askConfirm(a, eur) {
    if (!nba.box) return;
    var box = el('div', { class: 'ppme-confirm', role: 'alertdialog' });
    box.appendChild(el('p', {}, N.confirm(fmtEur(eur))));
    var bar = el('div', { class: 'ppme-nba-bar' });
    var yes = el('button', { type: 'button', class: 'ppme-go' }, N.confirmBtn);
    var no = el('button', { type: 'button' }, N.cancel);
    yes.onclick = function () { box.remove(); runAction(a, true); };
    no.onclick = function () { box.remove(); };
    bar.appendChild(yes);
    bar.appendChild(no);
    box.appendChild(bar);
    nba.box.appendChild(box);
  }
  function safeUrl(u) { return /^https?:\/\//i.test(String(u || '')) ? String(u) : ''; }
  function renderDeliverable(box, m) {
    box.appendChild(el('strong', {}, m.title || ''));
    box.appendChild(el('div', { class: 'ppme-text ppme-doc' }, m.text || ''));
    var copy = el('button', { type: 'button', class: 'ppme-link' }, N.copy);
    copy.onclick = function () {
      navigator.clipboard.writeText(m.text || '').then(function () { copy.textContent = N.copied; });
    };
    box.appendChild(copy);
    if (m.notes) box.appendChild(el('p', { class: 'ppme-why' }, N.check + m.notes));
  }
  function renderResearch(box, m, title) {
    var byN = {};
    (m.sources || []).forEach(function (s) { byN[s.n] = s; });
    if (title) box.appendChild(el('strong', {}, title));
    box.appendChild(el('div', { class: 'ppme-text' }, m.text || ''));
    var ul = el('ul', { class: 'ppme-findings' });
    (m.findings || []).forEach(function (f) {
      var li = el('li', {}, f.text);
      (f.sources || []).forEach(function (n) {
        var s = byN[n];
        if (!s || !safeUrl(s.url)) return;
        li.appendChild(document.createTextNode(' '));
        li.appendChild(el('a', { href: safeUrl(s.url), target: '_blank', rel: 'noopener noreferrer', class: 'ppme-src', title: s.title || s.url }, '[' + n + ']'));
      });
      ul.appendChild(li);
    });
    if ((m.findings || []).length) box.appendChild(ul);
    if (m.decision_impact) box.appendChild(el('p', { class: 'ppme-impact' }, N.impact + m.decision_impact));
    if ((m.sources || []).length) {
      var det = el('details', { class: 'ppme-sources' });
      det.appendChild(el('summary', {}, N.sources + ' (' + m.sources.length + ')'));
      var ol = el('ol', {});
      m.sources.forEach(function (s) {
        var li = el('li', {});
        if (safeUrl(s.url)) li.appendChild(el('a', { href: safeUrl(s.url), target: '_blank', rel: 'noopener noreferrer' }, s.title || s.url));
        ol.appendChild(li);
      });
      det.appendChild(ol);
      box.appendChild(det);
    }
  }
  /* ── Librairie : agents codés par Stan, essayés sur un dossier, partagés par leur créateur ── */
  var L = en ? {
    tabChat: '💬 Conversation', tabLib: '📚 Library', loading: 'Loading…',
    intro: 'Agents coded by Stan for tasks he could not do yet. Each one is tried on a deal, then shared with every fund by its creator. It runs isolated, with no access to anything but the current deal.',
    create: '🛠️ Create a custom agent', taskPh: 'e.g. “Audit the tech stack and tech hiring of the main competitors”',
    build: function (eur) { return 'Code and try the agent · ≈ ' + eur + ' €'; },
    empty: 'The library is empty: create the first agent.', run: 'Run on this deal', code: 'View code', hideCode: 'Hide code',
    validate: 'Approve and share', improve: 'Improve', discard: 'Discard', retire: 'Remove from library',
    feedbackPh: 'What should be improved…', send: 'Send to Stan',
    shared: 'Shared with all funds', draft: 'Draft — visible to your fund', mine: 'created by you',
    uses: function (n) { return n + (n === 1 ? ' run' : ' runs'); }, pendingV: function (v) { return 'Version ' + v + ' awaiting approval'; },
    testOk: 'Trial on this deal succeeded', testKo: 'The trial failed: ',
    built: function (name, v) { return '🛠️ Agent coded: ' + name + ' (v' + v + ')'; },
    states: { shared: 'Shared with all funds', discarded: 'Discarded' },
    sharedToast: 'Agent shared with every fund.', discardedToast: 'Done.'
  } : {
    tabChat: '💬 Conversation', tabLib: '📚 Librairie', loading: 'Chargement…',
    intro: 'Des agents codés par Stan pour des tâches qu’il ne savait pas encore faire. Chacun est essayé sur un dossier, puis partagé avec tous les fonds par son créateur. Il tourne isolé, sans accès à rien d’autre que le dossier en cours.',
    create: '🛠️ Créer un agent sur mesure', taskPh: 'ex. « Audite la stack technique et les recrutements tech des principaux concurrents »',
    build: function (eur) { return 'Coder et essayer l’agent · ≈ ' + eur + ' €'; },
    empty: 'La librairie est vide : créez le premier agent.', run: 'Lancer sur ce dossier', code: 'Voir le code', hideCode: 'Masquer le code',
    validate: 'Valider et partager', improve: 'Améliorer', discard: 'Abandonner', retire: 'Retirer de la librairie',
    feedbackPh: 'Ce qu’il faut améliorer…', send: 'Envoyer à Stan',
    shared: 'Partagé avec tous les fonds', draft: 'Brouillon — visible par votre fonds', mine: 'créé par vous',
    uses: function (n) { return n + (n > 1 ? ' utilisations' : ' utilisation'); }, pendingV: function (v) { return 'Version ' + v + ' à valider'; },
    testOk: 'Essai réussi sur ce dossier', testKo: 'L’essai a échoué : ',
    built: function (name, v) { return '🛠️ Agent codé : ' + name + ' (v' + v + ')'; },
    states: { shared: 'Partagé avec tous les fonds', discarded: 'Abandonné' },
    sharedToast: 'Agent partagé avec tous les fonds.', discardedToast: 'C’est fait.'
  };
  var lib = { box: null, data: null, state: {} };
  function loadLibrary() {
    if (!lib.box) return;
    if (!lib.data) { lib.box.innerHTML = ''; lib.box.appendChild(el('div', { class: 'ppme-wait' }, L.loading)); }
    api('/library').then(function (j) {
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      lib.data = j;
      renderLibrary();
    }).catch(function () {});
  }
  function renderLibrary() {
    var box = lib.box;
    if (!box || !lib.data) return;
    box.innerHTML = '';
    box.appendChild(el('p', { class: 'ppme-hint' }, L.intro));
    var create = el('details', { class: 'ppme-create' });
    create.appendChild(el('summary', {}, L.create));
    var task = el('textarea', { rows: '3', placeholder: L.taskPh, 'aria-label': L.create });
    var go = el('button', { type: 'button', class: 'ppme-go' }, L.build(fmtEur(lib.data.build_eur)));
    go.onclick = function () {
      if (task.value.trim().length < 10) { task.focus(); return; }
      go.disabled = true;
      buildAgent({ task: task.value.trim() }, function (ok) { go.disabled = false; if (ok) task.value = ''; });
    };
    create.appendChild(task);
    create.appendChild(go);
    box.appendChild(create);
    var agents = lib.data.agents || [];
    if (!agents.length) box.appendChild(el('p', { class: 'ppme-why' }, L.empty));
    agents.forEach(function (a) { box.appendChild(agentCard(a)); });
  }
  function agentCard(a) {
    var card = el('div', { class: 'ppme-agent' });
    card.appendChild(el('strong', {}, a.name));
    if (a.description) card.appendChild(el('p', { class: 'ppme-why' }, a.description));
    var meta = [a.status === 'shared' ? L.shared : L.draft, 'v' + a.version, L.uses(a.uses), '≈ ' + fmtEur(a.est_eur) + ' €'];
    if (a.mine) meta.push(L.mine);
    card.appendChild(el('div', { class: 'ppme-est' }, meta.join(' · ')));
    if (a.mine && a.test && !a.test.ok && a.status === 'draft') card.appendChild(el('p', { class: 'ppme-stale' }, L.testKo + (a.test.error || '')));
    if (a.pending) {
      card.appendChild(el('p', { class: 'ppme-stale' }, L.pendingV(a.pending.version)
        + (a.pending.test && !a.pending.test.ok ? ' — ' + L.testKo + (a.pending.test.error || '') : '')));
    }
    var bar = el('div', { class: 'ppme-nba-bar' });
    if (a.status === 'shared' || (a.test && a.test.ok)) {
      var run = el('button', { type: 'button', class: 'ppme-go' }, L.run);
      run.onclick = function () { runAgent(a, false, run, card); };
      bar.appendChild(run);
    }
    var code = el('button', { type: 'button' }, L.code);
    code.onclick = function () { toggleCode(a, card, code); };
    bar.appendChild(code);
    var testOk = a.pending ? a.pending.test && a.pending.test.ok : a.status === 'draft' && a.test && a.test.ok;
    if (a.mine && testOk) {
      var share = el('button', { type: 'button' }, L.validate);
      share.onclick = function () { agentDecision(a.id, 'validate', share); };
      bar.appendChild(share);
    }
    var better = el('button', { type: 'button' }, L.improve);
    better.onclick = function () { improveForm(a.id, card); };
    bar.appendChild(better);
    if (a.mine) {
      var drop = el('button', { type: 'button' }, a.pending || a.status === 'draft' ? L.discard : L.retire);
      drop.onclick = function () { agentDecision(a.id, 'discard', drop); };
      bar.appendChild(drop);
    }
    card.appendChild(bar);
    return card;
  }
  function toggleCode(a, card, btn) {
    var open = card.querySelector('.ppme-code');
    if (open) { open.remove(); btn.textContent = L.code; return; }
    api('/agents/' + a.id).then(function (j) {
      if (!j.ok) { toast(N.failed + (j.detail || j.status)); return; }
      card.appendChild(el('pre', { class: 'ppme-code' }, j.pending_code || j.code || ''));
      btn.textContent = L.hideCode;
    });
  }
  function improveForm(aid, container) {
    if (container.querySelector('.ppme-improve')) return;
    var form = el('div', { class: 'ppme-improve' });
    var text = el('textarea', { rows: '3', placeholder: L.feedbackPh, 'aria-label': L.improve });
    var send = el('button', { type: 'button', class: 'ppme-go' }, L.send);
    send.onclick = function () {
      if (text.value.trim().length < 5) { text.focus(); return; }
      send.disabled = true;
      buildAgent({ agent_id: aid, feedback: text.value.trim() }, function (ok) { send.disabled = false; if (ok) form.remove(); });
    };
    form.appendChild(text);
    form.appendChild(send);
    container.appendChild(form);
    text.focus();
  }
  function showChat() { if (chat.show) chat.show('chat'); }
  function buildAgent(body, done) {
    api('/agents/build', 'POST', body).then(function (j) {
      done(!!j.ok);
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      showChat();
      (j.messages || []).forEach(renderMessage);
      track(j.run_id, { op: 'build', title: (j.messages && j.messages[0] && j.messages[0].text) || L.create });
    }).catch(function (e) { done(false); toast(N.failed + e); });
  }
  function runAgent(a, confirmed, btn, container) {
    if (btn) btn.disabled = true;
    api('/agents/' + a.id + '/run', 'POST', { confirm: !!confirmed }).then(function (j) {
      if (btn) btn.disabled = false;
      if (j.needs_confirm) {
        var box = el('div', { class: 'ppme-confirm', role: 'alertdialog' });
        box.appendChild(el('p', {}, N.confirm(fmtEur(j.est_eur))));
        var bar = el('div', { class: 'ppme-nba-bar' });
        var yes = el('button', { type: 'button', class: 'ppme-go' }, N.confirmBtn);
        var no = el('button', { type: 'button' }, N.cancel);
        yes.onclick = function () { box.remove(); runAgent(a, true, null, container); };
        no.onclick = function () { box.remove(); };
        bar.appendChild(yes);
        bar.appendChild(no);
        box.appendChild(bar);
        container.appendChild(box);
        return;
      }
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      showChat();
      (j.messages || []).forEach(renderMessage);
      track(j.run_id, { op: 'agent', title: a.name });
    }).catch(function (e) { if (btn) btn.disabled = false; toast(N.failed + e); });
  }
  function agentDecision(aid, what, btn) {
    if (btn) btn.disabled = true;
    api('/agents/' + aid + '/' + what, 'POST', {}).then(function (j) {
      if (btn) btn.disabled = false;
      if (!j.ok) { toast(N.failed + (j.detail || j.error || j.status)); return; }
      lib.state[aid] = what === 'validate' ? 'shared' : 'discarded';
      toast(what === 'validate' ? L.sharedToast : L.discardedToast);
      Array.prototype.forEach.call(document.querySelectorAll('.ppme-agent-acts[data-aid="' + aid + '"]'), function (n) {
        n.replaceWith(el('span', { class: 'ppme-status accepted' }, L.states[lib.state[aid]]));
      });
      loadLibrary();
    }).catch(function (e) { if (btn) btn.disabled = false; toast(N.failed + e); });
  }
  function renderAgentDraft(box, m) {
    var a = m.agent || {};
    box.appendChild(el('strong', {}, L.built(a.name || '', a.version || 1)));
    if (a.description) box.appendChild(el('p', { class: 'ppme-why' }, a.description));
    if (m.error) box.appendChild(el('p', { class: 'ppme-stale' }, L.testKo + m.error));
    else {
      box.appendChild(el('div', { class: 'ppme-op-h' }, L.testOk));
      renderResearch(box, m, '');
      if (m.deliverable) renderDeliverable(box, { title: m.deliverable.title, text: m.deliverable.content });
    }
    if (lib.state[a.id]) { box.appendChild(el('span', { class: 'ppme-status accepted' }, L.states[lib.state[a.id]])); return; }
    var bar = el('div', { class: 'ppme-nba-bar ppme-agent-acts', 'data-aid': a.id || '' });
    var mine = a.by === state.email;
    if (mine && a.ok) {
      var share = el('button', { type: 'button', class: 'ppme-go' }, L.validate);
      share.onclick = function () { agentDecision(a.id, 'validate', share); };
      bar.appendChild(share);
    }
    var better = el('button', { type: 'button' }, L.improve);
    better.onclick = function () { improveForm(a.id, box); };
    bar.appendChild(better);
    if (mine) {
      var drop = el('button', { type: 'button' }, L.discard);
      drop.onclick = function () { agentDecision(a.id, 'discard', drop); };
      bar.appendChild(drop);
    }
    box.appendChild(bar);
  }
  function renderAgentResult(box, m) {
    var a = m.agent || {};
    box.appendChild(el('strong', {}, '🧩 ' + (a.name || '')));
    if (m.error) { box.appendChild(el('p', { class: 'ppme-stale' }, N.failed + m.error)); return; }
    renderResearch(box, m, '');
    if (m.deliverable) renderDeliverable(box, { title: m.deliverable.title, text: m.deliverable.content });
  }
  function openChat() {
    if (chat.panel) { chat.panel.remove(); chat.panel = null; chat.list = null; nba.box = null; lib.box = null; chat.show = null; return; }
    var panel = el('aside', { class: 'ppme-chat', role: 'complementary', 'aria-label': C.title });
    var head = el('div', { class: 'ppme-card-h' });
    head.appendChild(el('strong', {}, C.title));
    var x = el('button', { type: 'button', class: 'ppme-x', 'aria-label': T.close }, '×');
    x.onclick = openChat;
    head.appendChild(x);
    panel.appendChild(head);
    var tabs = el('div', { class: 'ppme-tabs', role: 'tablist' });
    var tabChat = el('button', { type: 'button', role: 'tab', 'aria-selected': 'true' }, L.tabChat);
    var tabLib = el('button', { type: 'button', role: 'tab', 'aria-selected': 'false' }, L.tabLib);
    tabs.appendChild(tabChat);
    tabs.appendChild(tabLib);
    panel.appendChild(tabs);
    var view = el('div', { class: 'ppme-view' });
    lib.box = el('div', { class: 'ppme-view ppme-lib', role: 'tabpanel', hidden: '' });
    chat.show = function (which) {
      view.hidden = which !== 'chat';
      lib.box.hidden = which !== 'lib';
      tabChat.setAttribute('aria-selected', String(which === 'chat'));
      tabLib.setAttribute('aria-selected', String(which === 'lib'));
      if (which === 'lib') loadLibrary();
    };
    tabChat.onclick = function () { chat.show('chat'); };
    tabLib.onclick = function () { chat.show('lib'); };
    view.appendChild(el('p', { class: 'ppme-hint' }, C.hint));
    nba.box = el('section', { class: 'ppme-nba', 'aria-label': N.title });
    view.appendChild(nba.box);
    chat.list = el('div', { class: 'ppme-msgs' });
    view.appendChild(chat.list);
    var form = el('form', { class: 'ppme-form' });
    var input = el('textarea', { rows: '3', placeholder: C.placeholder, 'aria-label': C.placeholder });
    var send = el('button', { type: 'submit', class: 'ppme-save' }, C.send);
    form.appendChild(input);
    form.appendChild(send);
    form.onsubmit = function (e) {
      e.preventDefault();
      var message = input.value.trim();
      if (!message || send.disabled) return;
      send.disabled = true;
      renderMessage({ type: 'message', role: 'user', by: state.email, at: new Date().toISOString(), text: message });
      input.value = '';
      var wait = el('div', { class: 'ppme-msg stan ppme-wait' }, C.thinking);
      chat.list.appendChild(wait);
      chat.list.scrollTop = chat.list.scrollHeight;
      api('/chat', 'POST', { message: message }).then(function (j) {
        wait.remove();
        send.disabled = false;
        if (!j.ok) { toast(T.error + (j.detail || j.error || j.status)); return; }
        (j.messages || []).slice(1).forEach(renderMessage);
      }).catch(function (err) { wait.remove(); send.disabled = false; toast(T.error + err); });
    };
    input.addEventListener('keydown', function (e) { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) form.requestSubmit(); });
    view.appendChild(form);
    panel.appendChild(view);
    panel.appendChild(lib.box);
    document.body.appendChild(panel);
    chat.panel = panel;
    api('/chat').then(function (j) {
      if (!j.ok) return;
      (j.messages || []).forEach(function (m) {
        if (m.type === 'decision') chat.decisions[m.pid] = m.decision;
        if (m.type === 'agent_decision') lib.state[m.aid] = m.decision;
      });
      (j.messages || []).forEach(renderMessage);
    });
    loadNext();
    input.focus();
  }

  function buildPill() {
    if (document.querySelector('.ppme-pill')) return;
    var pill = el('div', { class: 'ppme-pill' });
    var talk = el('button', { type: 'button' }, C.chat);
    talk.onclick = openChat;
    pill.appendChild(talk);
    var edit = el('button', { type: 'button' }, T.editMemo);
    var versions = el('button', { type: 'button' }, T.versions);
    edit.onclick = function () {
      if (state.open) return;
      state.editing = !state.editing;
      edit.textContent = state.editing ? T.stopEdit : T.editMemo;
      decorate();
    };
    versions.onclick = openVersions;
    pill.appendChild(edit);
    pill.appendChild(versions);
    document.body.appendChild(pill);
  }
  function checkAccess() {
    if (state.role || !session()) return;
    api('/access').then(function (a) {
      if (!a.ok) return;
      state.role = a.role;
      state.email = a.email;
      if (a.head) state.head = a.head;
      injectCss();
      buildPill();
      decorate();
    }).catch(function () {});
  }
  function injectCss() {
    if (document.getElementById('ppme-css')) return;
    var css = el('style', { id: 'ppme-css' });
    css.textContent = [
      '.ppme-sec{position:relative}',
      '.ppme-edit{position:absolute;top:10px;right:10px;z-index:5;border:1px solid #BFE6CF;background:#EAF6EF;color:#0E6B37;border-radius:999px;padding:5px 12px;font-weight:600;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-edit:hover{background:#12A150;color:#fff;border-color:#12A150}',
      '.ppme-badge{display:inline-block;margin:4px 0 10px;padding:3px 10px;border-radius:999px;background:#FFF8E8;color:#7A5A00;font-size:12px}',
      '.ppme-editing{outline:2px solid #12A150;outline-offset:6px;border-radius:6px}',
      '.ppme-toolbar{position:sticky;top:8px;z-index:6;display:flex;gap:6px;align-items:center;margin:0 0 12px;padding:6px;background:#fff;border:1px solid #E3E8F0;border-radius:12px;box-shadow:0 6px 18px rgba(15,29,51,.12)}',
      '.ppme-toolbar button{border:1px solid #E3E8F0;background:#fff;border-radius:8px;min-width:32px;height:30px;padding:0 10px;font-weight:600;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-save{background:#12A150!important;color:#fff!important;border-color:#12A150!important;margin-left:auto}',
      '.ppme-pill{position:fixed;left:16px;bottom:16px;z-index:2147483000;display:flex;gap:6px;padding:6px;background:#fff;border:1px solid #E3E8F0;border-radius:999px;box-shadow:0 8px 24px rgba(15,29,51,.16)}',
      '.ppme-pill button{border:0;background:#F2F8F4;color:#0E6B37;border-radius:999px;padding:8px 14px;font-weight:700;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-toast,.ppme-preview{position:fixed;left:50%;transform:translateX(-50%);bottom:76px;z-index:2147483001;display:flex;gap:10px;align-items:center;max-width:min(680px,calc(100vw - 32px));padding:10px 14px;background:#16233A;color:#fff;border-radius:12px;font-size:13.5px;box-shadow:0 10px 30px rgba(15,29,51,.3)}',
      '.ppme-preview{top:16px;bottom:auto;background:#FFF8E8;color:#5C4400;border:1px solid #F3D08A}',
      '.ppme-toast button,.ppme-preview button{border:0;border-radius:999px;padding:6px 12px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer;background:#fff;color:#16233A}',
      '.ppme-x{background:none!important;color:inherit!important;font-size:18px!important;padding:0 4px!important}',
      '.ppme-modal{position:fixed;inset:0;z-index:2147483002;display:grid;place-items:center;background:rgba(15,29,51,.45);padding:16px}',
      '.ppme-card{width:min(640px,100%);max-height:80vh;overflow:auto;background:#fff;border-radius:16px;padding:18px 20px;color:#16233A}',
      '.ppme-card-h{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;font-size:16px}',
      '.ppme-list{list-style:none;margin:0;padding:0}',
      '.ppme-list li{display:flex;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #EEF2F7;font-size:13.5px}',
      '.ppme-n{font-weight:700;color:#0E6B37;min-width:34px}',
      '.ppme-what{flex:1;min-width:0}',
      '.ppme-cur{font-size:12px;color:#0E6B37;background:#EAF6EF;border-radius:999px;padding:2px 9px}',
      '.ppme-list button{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:5px 12px;font-weight:600;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-chat{position:fixed;top:0;right:0;bottom:0;z-index:2147483003;width:min(440px,100vw);display:flex;flex-direction:column;background:#fff;border-left:1px solid #E3E8F0;box-shadow:-12px 0 32px rgba(15,29,51,.14);padding:16px;box-sizing:border-box;color:#16233A}',
      '.ppme-hint{margin:0 0 10px;font-size:12.5px;color:#61708A}',
      '.ppme-msgs{flex:1;overflow:auto;display:flex;flex-direction:column;gap:10px;padding:4px 2px}',
      '.ppme-msg{max-width:92%;padding:10px 12px;border-radius:12px;font-size:13.5px;line-height:1.5}',
      '.ppme-msg.me{align-self:flex-end;background:#EAF6EF}',
      '.ppme-msg.stan{align-self:flex-start;background:#F6F8FB;border:1px solid #EEF2F7}',
      '.ppme-who{font-size:11.5px;color:#61708A;margin-bottom:4px}',
      '.ppme-text{white-space:pre-wrap}',
      '.ppme-wait{color:#61708A;font-style:italic}',
      '.ppme-prop{margin-top:10px;padding:10px;border:1px solid #BFE6CF;border-radius:10px;background:#fff}',
      '.ppme-why{margin:4px 0 8px;font-size:12.5px;color:#4B5E78}',
      '.ppme-op{margin:8px 0;padding-top:8px;border-top:1px dashed #E3E8F0}',
      '.ppme-op-h{font-size:12px;font-weight:700;color:#0E6B37;margin-bottom:4px}',
      '.ppme-before{font-size:12.5px;color:#B42318;text-decoration:line-through;margin-bottom:4px}',
      '.ppme-after{font-size:12.5px;color:#0E6B37}',
      '.ppme-link{border:0;background:none;color:#3B4D66;text-decoration:underline;font-size:12px;padding:4px 0;cursor:pointer;font-family:inherit}',
      '.ppme-prop-actions{display:flex;gap:8px;margin-top:8px}',
      '.ppme-prop-actions button{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:6px 14px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-status{display:inline-block;margin-top:8px;font-size:12px;font-weight:700;border-radius:999px;padding:3px 10px}',
      '.ppme-status.accepted{background:#EAF6EF;color:#0E6B37}',
      '.ppme-status.declined{background:#EEF2F7;color:#61708A}',
      '.ppme-form{display:flex;gap:8px;align-items:flex-end;margin-top:10px}',
      '.ppme-form textarea{flex:1;resize:vertical;min-height:64px;border:1px solid #E3E8F0;border-radius:12px;padding:10px;font-family:inherit;font-size:13.5px}',
      '.ppme-form button{border:0;border-radius:999px;padding:10px 16px;font-weight:700;font-size:13px;font-family:inherit;cursor:pointer}',
      '.ppme-hl{outline:3px solid #E0A526!important;outline-offset:3px;background:#FFF8E8!important;transition:background .3s}',
      '.ppme-nba{flex:none;max-height:44vh;overflow:auto;margin:0 0 10px;padding:12px;border:1px solid #F3D08A;border-radius:12px;background:#FFFBF0;font-size:13px;line-height:1.45}',
      '.ppme-nba-h{display:block;width:100%;text-align:left;border:0;background:none;padding:0;margin-bottom:6px;font-weight:800;font-size:13.5px;font-family:inherit;color:inherit;cursor:pointer}',
      '.ppme-nba-folded{font-size:12.5px;color:#3B4D66;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
      '.ppme-nba-meta{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:4px}',
      '.ppme-chip{font-size:11.5px;font-weight:700;border-radius:999px;padding:2px 9px;background:#EEF2F7;color:#3B4D66}',
      '.ppme-chip.sig-go{background:#EAF6EF;color:#0E6B37}',
      '.ppme-chip.sig-wait{background:#FFF1D6;color:#7A5A00}',
      '.ppme-chip.sig-stop{background:#FDECEC;color:#B42318}',
      '.ppme-unc{margin:6px 0;font-size:12.5px}',
      '.ppme-nba-act{margin-top:8px;padding:10px;border-radius:10px;background:#fff;border:1px solid #EEF2F7}',
      '.ppme-est{font-size:12px;color:#61708A;margin-top:4px}',
      '.ppme-stale{font-size:12px;color:#7A5A00;margin:8px 0 0}',
      '.ppme-nba-run{font-size:12.5px;color:#0E6B37;font-weight:700;margin:2px 0 6px}',
      '.ppme-nba-bar{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}',
      '.ppme-nba-bar button,.ppme-nba>.ppme-go{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:7px 14px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-nba .ppme-go{background:#12A150;color:#fff;border-color:#12A150}',
      '.ppme-nba button:disabled{opacity:.55;cursor:wait}',
      '.ppme-confirm{margin-top:10px;padding:10px;border-radius:10px;background:#FFF1D6}',
      '.ppme-confirm p{margin:0}',
      '.ppme-cite{border:0;background:#EEF2F7;color:#3B4D66;border-radius:6px;padding:0 6px;margin:0 1px;font-size:11.5px;font-family:inherit;cursor:pointer}',
      '.ppme-doc{background:#fff;border:1px solid #EEF2F7;border-radius:8px;padding:8px 10px;margin:6px 0;max-height:320px;overflow:auto}',
      '.ppme-findings{margin:6px 0;padding-left:18px}',
      '.ppme-findings li{margin:4px 0;font-size:13px;line-height:1.45;color:inherit}',
      '.ppme-src{font-size:11.5px;color:#3B4D66}',
      '.ppme-impact{font-size:12.5px;font-weight:600;margin:6px 0}',
      '.ppme-sources{font-size:12px;margin-top:6px}',
      '.ppme-sources summary{font-size:12.5px;font-weight:600;cursor:pointer}',
      '.ppme-sources li{font-size:12px;margin:2px 0}',
      '.ppme-sources ol{padding-left:18px;margin:4px 0}',
      '.ppme-sources a{color:#3B4D66;word-break:break-word}',
      '.ppme-tabs{display:flex;gap:6px;margin:0 0 10px}',
      '.ppme-tabs button{flex:1;border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:7px 10px;font-weight:700;font-size:12.5px;font-family:inherit;color:#3B4D66;cursor:pointer}',
      '.ppme-tabs button[aria-selected="true"]{background:#16233A;color:#fff;border-color:#16233A}',
      '.ppme-view{flex:1;min-height:0;display:flex;flex-direction:column}',
      '.ppme-view[hidden]{display:none!important}',
      '.ppme-lib{overflow:auto;gap:10px}',
      '.ppme-create{padding:10px 12px;border:1px dashed #BFE6CF;border-radius:12px;background:#F7FCF9}',
      '.ppme-create summary{font-weight:700;font-size:13px;cursor:pointer}',
      '.ppme-create textarea,.ppme-improve textarea{width:100%;box-sizing:border-box;margin:8px 0;border:1px solid #E3E8F0;border-radius:10px;padding:8px;font-family:inherit;font-size:13px;resize:vertical}',
      '.ppme-create .ppme-go,.ppme-improve .ppme-go{border:0;background:#12A150;color:#fff;border-radius:999px;padding:7px 14px;font-weight:700;font-size:12.5px;font-family:inherit;cursor:pointer}',
      '.ppme-agent{padding:12px;border:1px solid #E3E8F0;border-radius:12px;background:#fff;font-size:13px}',
      '.ppme-msg .ppme-nba-bar button,.ppme-agent .ppme-nba-bar button,.ppme-confirm .ppme-nba-bar button{border:1px solid #E3E8F0;background:#fff;border-radius:999px;padding:6px 12px;font-weight:700;font-size:12px;font-family:inherit;cursor:pointer}',
      '.ppme-agent .ppme-nba-bar .ppme-go,.ppme-msg .ppme-nba-bar .ppme-go,.ppme-confirm .ppme-nba-bar .ppme-go{background:#12A150;color:#fff;border-color:#12A150}',
      '.ppme-chat summary{font-size:12.5px!important;line-height:1.4!important;font-weight:600}',
      '.ppme-chat .ppme-create summary{font-size:13px!important;font-weight:700}',
      '.ppme-code{max-height:300px;overflow:auto;margin:8px 0 0;padding:10px;background:#0F1D33;color:#E3E8F0;border-radius:10px;font-size:11.5px;line-height:1.45;white-space:pre}',
      '.ppme-improve{margin-top:8px}'
    ].join('\n');
    document.head.appendChild(css);
  }

  syncLatest().then(checkAccess);
  // connexion faite dans le panneau Stan (cookie posé) : l'édition s'ouvre au retour
  window.addEventListener('focus', checkAccess);
  document.addEventListener('visibilitychange', function () { if (!document.hidden) checkAccess(); });
})();
